# -*- coding: utf-8 -*-
"""2.c. "corregido".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13m16ZqZNl1KRavabj3xFWBZ1a6oiHm39
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
from random import random, seed
from math import log
from scipy.integrate import solve_ivp

params = {
    "A": 1.0,
    "lambda_U": 0.2,
    "lambda_Np": 0.3,
    "B": 0.1
}

t_start = 0.0
t_end = 30.0
u0 = np.array([10, 10, 10], dtype=int)
n_realizations = 5
rng_seed = 42

R = [
    np.array([+1,  0,  0], dtype=int),
    np.array([-1, +1,  0], dtype=int),
    np.array([ 0, -1, +1], dtype=int),
    np.array([ 0,  0, -1], dtype=int),
]

def propensities(state, p):
    U, Np, Pu = state
    return np.array([
        p["A"],
        p["lambda_U"] * U,
        p["lambda_Np"] * Np,
        p["B"] * Pu
    ], dtype=float)

def gillespie_run(u0, p, t_end, t_start=0.0, rng_seed=None):
    """Corre una realización del algoritmo de Gillespie.
    Devuelve arrays de tiempos y estados (cada fila: [U, Np, Pu]).
    """
    if rng_seed is not None:
        seed(rng_seed)  # semilla para random.random

    t = t_start
    state = np.array(u0, dtype=int)
    times = [t]
    states = [state.copy()]

    while t < t_end:
        a = propensities(state, p)
        a0 = a.sum()
        if a0 <= 0:
            break

        u = random()
        while u == 0.0:
            u = random()
        tau = -log(u) / a0

        r = random() * a0
        cumulative = 0.0
        reaction_index = None
        for i, ai in enumerate(a):
            cumulative += ai
            if r <= cumulative:
                reaction_index = i
                break
        if reaction_index is None:
            reaction_index = len(a) - 1

        state = state + R[reaction_index]
        state = np.maximum(state, 0)

        t += tau
        times.append(t)
        states.append(state.copy())

    return np.array(times), np.array(states, dtype=int)

def deterministic_rhs(t, y, p):
    U, Np, Pu = y
    dU = p["A"] - p["lambda_U"] * U
    dNp = p["lambda_U"] * U - p["lambda_Np"] * Np
    dPu = p["lambda_Np"] * Np - p["B"] * Pu
    return [dU, dNp, dPu]

t_eval = np.linspace(t_start, t_end, 1001)
sol = solve_ivp(deterministic_rhs, [t_start, t_end], u0.astype(float), args=(params,), t_eval=t_eval, rtol=1e-8)

all_ts = []
all_states = []

for i in range(n_realizations):
    # usar semillas distintas
    ts, states = gillespie_run(u0, params, t_end, t_start=t_start, rng_seed=(rng_seed + i if rng_seed is not None else None))
    all_ts.append(ts)
    all_states.append(states)

fig, axes = plt.subplots(3, 1, figsize=(8, 10), sharex=True)
labels = ["U", "Np", "Pu"]
colors = None

for idx, ax in enumerate(axes):
    ax.plot(sol.t, sol.y[idx, :], lw=2, label=f"Determinista {labels[idx]}")
    for j in range(n_realizations):
        ts = all_ts[j]
        states = all_states[j][:, idx]
        ax.step(ts, states, where='post', alpha=0.8, label=(f"Estocástica {labels[idx]} #{j+1}" if idx==0 and j==0 else None))
    ax.set_ylabel(f"N({labels[idx]})")
    ax.grid(True)

axes[-1].set_xlabel("t")
axes[0].legend(loc='upper right')
plt.suptitle("Comparación: solución determinista y 5 trayectorias Gillespie")
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig("2.c.png")
#plt.show()
plt.close()

