{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPHBJDcFWJ6w1SpdNNVnada",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/mcramireza1/Grupo7_Metodos2/blob/main/T5/Punto_1_T5.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 15,
      "metadata": {
        "id": "0_Z1ZNpOadhT"
      },
      "outputs": [],
      "source": [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# ===============================\n",
        "# Parámetros del modelo\n",
        "# ===============================\n",
        "N = 50          # Tamaño de la red NxN\n",
        "J = 1           # Interacción\n",
        "beta = 0.5      # Inverso de la temperatura (β = 1/T)\n",
        "epochs = 300000 # Número de pasos de Monte Carlo\n",
        "\n",
        "# ===============================\n",
        "# Funciones auxiliares\n",
        "# ===============================\n",
        "def energia_local(lattice, i, j):\n",
        "    \"\"\"\n",
        "    Calcula la energía local de un espín en (i,j)\n",
        "    con condiciones de frontera periódicas.\n",
        "    \"\"\"\n",
        "    s = lattice[i, j]\n",
        "    # Vecinos (arriba, abajo, izq, der) con frontera periódica\n",
        "    nb = lattice[(i+1)%N, j] + lattice[(i-1)%N, j] + lattice[i, (j+1)%N] + lattice[i, (j-1)%N]\n",
        "    return -J * s * nb\n",
        "\n",
        "def energia_total(lattice):\n",
        "    \"\"\"\n",
        "    Calcula la energía total de la red.\n",
        "    \"\"\"\n",
        "    E = 0\n",
        "    for i in range(N):\n",
        "        for j in range(N):\n",
        "            E += energia_local(lattice, i, j)\n",
        "    return E / 2.0  # cada interacción se cuenta dos veces\n",
        "\n",
        "def magnetizacion(lattice):\n",
        "    return np.sum(lattice)\n",
        "\n",
        "# ===============================\n",
        "# Inicialización\n",
        "# ===============================\n",
        "# Estado inicial aleatorio (temperatura infinita)\n",
        "lattice = np.random.choice([-1, 1], size=(N,N))\n",
        "\n",
        "# Guardamos imágenes del estado inicial\n",
        "lattice_inicial = lattice.copy()\n",
        "\n",
        "# ===============================\n",
        "# Simulación con Metropolis\n",
        "# ===============================\n",
        "E_list = []\n",
        "M_list = []\n",
        "\n",
        "E = energia_total(lattice)\n",
        "M = magnetizacion(lattice)\n",
        "\n",
        "E_list.append(E / (N*N))\n",
        "M_list.append(M / (N*N))\n",
        "\n",
        "for step in range(epochs):\n",
        "    # Escoger espín aleatorio\n",
        "    i = np.random.randint(0, N)\n",
        "    j = np.random.randint(0, N)\n",
        "\n",
        "    dE = -2 * energia_local(lattice, i, j)\n",
        "\n",
        "    # Regla de Metropolis\n",
        "    if dE <= 0 or np.random.rand() < np.exp(-beta*dE):\n",
        "        lattice[i, j] *= -1  # flip\n",
        "        E += dE\n",
        "        M += 2 * lattice[i,j]\n",
        "\n",
        "    # Guardar cada 100 pasos para graficar más suave\n",
        "    if step % 100 == 0:\n",
        "        E_list.append(E / (N*N))\n",
        "        M_list.append(M / (N*N))\n",
        "\n",
        "lattice_final = lattice.copy()\n",
        "\n",
        "# ===============================\n",
        "# Gráficas\n",
        "# ===============================\n",
        "\n",
        "fig, axs = plt.subplots(1, 3, figsize=(16,5))\n",
        "\n",
        "# Estado inicial\n",
        "axs[0].imshow(lattice_inicial, cmap=\"coolwarm\")\n",
        "axs[0].set_title(\"Antes\")\n",
        "axs[0].axis(\"off\")\n",
        "\n",
        "# Evolución energía y magnetización\n",
        "axs[1].plot(E_list, color=\"black\", label=\"Energía\")\n",
        "axs[1].plot(M_list, color=\"red\", label=\"Magnetización\")\n",
        "axs[1].set_xlabel(\"Épocas\")\n",
        "axs[1].legend()\n",
        "axs[1].set_title(\"Durante\")\n",
        "\n",
        "# Estado final\n",
        "axs[2].imshow(lattice_final, cmap=\"coolwarm\")\n",
        "axs[2].set_title(\"Después\")\n",
        "axs[2].axis(\"off\")\n",
        "\n",
        "plt.savefig(\"1.a.pdf\")\n",
        "plt.close(fig)\n",
        "#plt.show()"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# 1b\n",
        "\n",
        "# Simulación 2D del modelo de Ising usando Metropolis MCMC.\n",
        "# Calcula la capacidad calorífica Cv(β) = β^2 N^2 ( <E^2> - <E>^2 ) y guarda una gráfica\n",
        "\n",
        "!pip install numpy matplotlib numba\n",
        "import time                              # medir tiempo de ejecución\n",
        "import numpy as np                       # arrays y operaciones vectorizadas\n",
        "import matplotlib.pyplot as plt          # para graficar\n",
        "import csv                               # para guardar resultados en CSV\n",
        "import os                                # operaciones de sistema (crear carpeta)\n",
        "\n",
        "\n",
        "# Entrada y definición de parámetros\n",
        "\n",
        "N = 20                                   # Matriz cuadrada (N x N)\n",
        "J = 1.0                                  # acoplamiento entre vecinos (J>0 ferromagnético)\n",
        "beta_values = np.arange(0.10, 0.901, 0.01)  # rango de betas a explorar (0.10 a 0.90 paso 0.01)\n",
        "eq_sweeps = 200                          # sweeps para equilibrar en cada beta\n",
        "meas_sweeps = 400                        # sweeps durante la etapa de medida\n",
        "sample_interval = 5                      # guardar muestra cada 'sample_interval' sweeps\n",
        "output_dir = \"results_ising\"             # carpeta donde guardar resultados\n",
        "\n",
        "\n",
        "# Numba: intentamos usarlo para acelerar loops\n",
        "\n",
        "use_numba = False\n",
        "try:\n",
        "    from numba import njit\n",
        "    use_numba = True\n",
        "    # Nota: en algunas instalaciones de numba, np.random.random() funciona dentro de @njit;\n",
        "\n",
        "except Exception as e:\n",
        "    # Si no está instalado numba, seguimos con la versión numpy/pura.\n",
        "    print(\"numba no disponible — se usará la versión numpy (más lenta).\", e)\n",
        "\n",
        "\n",
        "# Funciones\n",
        "\n",
        "#Inicializamos matriz nxn con espines aleatorios. Entrega un array\n",
        "def init_spins_random(N):\n",
        "\n",
        "    # np.random.rand genera valores en [0,1); con <0.5 ponemos 1, sino -1.\n",
        "    spins = np.where(np.random.rand(N, N) < 0.5, 1, -1).astype(np.int8)\n",
        "    return spins\n",
        "\n",
        "#Calculo energía total como suma de vecinos derecha y abajo evitando repeticiones\n",
        "def total_energy_numpy(spins, J=1.0):\n",
        "\n",
        "    N = spins.shape[0]\n",
        "    energy = 0.0\n",
        "    # bucle doble\n",
        "    for i in range(N):\n",
        "        for j in range(N):\n",
        "            s = spins[i, j]\n",
        "            # vecinos: derecha (j+1) y abajo (i+1) con condiciones periódicas\n",
        "            energy -= J * s * (spins[i, (j + 1) % N] + spins[(i + 1) % N, j])\n",
        "    return energy\n",
        "\n",
        "# Ahora energía versión numba de total_energy\n",
        "if use_numba:\n",
        "    @njit\n",
        "    def total_energy_numba(spins, J=1.0):\n",
        "        N = spins.shape[0]\n",
        "        energy = 0.0\n",
        "        for i in range(N):\n",
        "            for j in range(N):\n",
        "                s = spins[i, j]\n",
        "                energy -= J * s * (spins[i, (j + 1) % N] + spins[(i + 1) % N, j])\n",
        "        return energy\n",
        "\n",
        "# Versión Metropolis sweep (numpy)\n",
        "def metropolis_sweep_numpy(spins, beta, J=1.0):\n",
        "    \"\"\"\n",
        "    Realiza un sweep de Metropolis: intenta voltear cada espín (orden i,j).\n",
        "    \"\"\"\n",
        "    N = spins.shape[0]\n",
        "    for i in range(N):\n",
        "        for j in range(N):\n",
        "            s = spins[i, j]\n",
        "            # suma de los 4 vecinos (periodic boundary conditions)\n",
        "            nb = spins[(i - 1) % N, j] + spins[(i + 1) % N, j] + spins[i, (j - 1) % N] + spins[i, (j + 1) % N]\n",
        "            dE = 2.0 * J * s * nb   # cambio de energia al voltear s -> -s\n",
        "            # criterio de Metropolis\n",
        "            if dE <= 0.0:\n",
        "                spins[i, j] = -s\n",
        "            else:\n",
        "                if np.random.rand() < np.exp(-beta * dE):\n",
        "                    spins[i, j] = -s\n",
        "\n",
        "# Versión Metropolis sweep (numba)\n",
        "if use_numba:\n",
        "    @njit\n",
        "    def metropolis_sweep_numba(spins, beta, J=1.0):\n",
        "        N = spins.shape[0]\n",
        "        for i in range(N):\n",
        "            for j in range(N):\n",
        "                s = spins[i, j]\n",
        "                nb = spins[(i - 1) % N, j] + spins[(i + 1) % N, j] + spins[i, (j - 1) % N] + spins[i, (j + 1) % N]\n",
        "                dE = 2.0 * J * s * nb\n",
        "                if dE <= 0.0:\n",
        "                    spins[i, j] = -s\n",
        "                else:\n",
        "                    # np.random.random() en numba genera un float en [0,1)\n",
        "                    if np.random.random() < np.exp(-beta * dE):\n",
        "                        spins[i, j] = -s\n",
        "\n",
        "# Selección numba o numpy\n",
        "if use_numba:\n",
        "    total_energy = total_energy_numba\n",
        "    metropolis_sweep = metropolis_sweep_numba\n",
        "else:\n",
        "    total_energy = total_energy_numpy\n",
        "    metropolis_sweep = metropolis_sweep_numpy\n",
        "\n",
        "\n",
        "# Cálculo del betha (Onsager) para J=1\n",
        "\n",
        "beta_crit_theory = 0.5 * np.log(1.0 + np.sqrt(2.0))\n",
        "\n",
        "\n",
        "# Simulacion: recorre bethas, equilibra, medida. Devuelve arrays (betas, Cv_list)\n",
        "\n",
        "def run_simulation(N, J, beta_values, eq_sweeps, meas_sweeps, sample_interval):\n",
        "\n",
        "    # Inicializamos resultados\n",
        "    Cv_list = []\n",
        "    betas_done = []\n",
        "    # Crear estado inicial aleatorio (equivalente a betha 0)\n",
        "    spins = init_spins_random(N)\n",
        "    start_total = time.time()\n",
        "\n",
        "    # iteramos sobre betas\n",
        "    for idx, beta in enumerate(beta_values):\n",
        "        t0 = time.time()\n",
        "        # 1) equilibración: eq_sweeps sweeps sin medir\n",
        "        for _ in range(eq_sweeps):\n",
        "            metropolis_sweep(spins, beta, J)\n",
        "\n",
        "        # 2) medición: realizamos meas_sweeps y guardamos muestras cada sample_interval\n",
        "        energies = []  # energías por espín muestreadas\n",
        "        for sweep in range(meas_sweeps):\n",
        "            metropolis_sweep(spins, beta, J)\n",
        "            if (sweep % sample_interval) == 0:\n",
        "                # total_energy devuelve energía total; convertimos a energía por espín\n",
        "                E_per_spin = total_energy(spins, J) / (N * N)\n",
        "                energies.append(E_per_spin)\n",
        "\n",
        "        energies = np.array(energies, dtype=np.float64)\n",
        "        # calcular momentos\n",
        "        E_mean = energies.mean()\n",
        "        E2_mean = (energies ** 2).mean()\n",
        "        # formula del enunciado: Cv = beta^2 * N^2 * ( <E^2> - <E>^2 )\n",
        "        Cv = (beta ** 2) * (N ** 2) * (E2_mean - E_mean ** 2)\n",
        "        Cv_list.append(Cv)\n",
        "        betas_done.append(beta)\n",
        "\n",
        "        t1 = time.time()\n",
        "        # imprimir progreso cada 5 betas o en el ultimo\n",
        "        if idx % 5 == 0 or idx == len(beta_values) - 1:\n",
        "            print(f\"[{idx+1}/{len(beta_values)}] beta={beta:.3f}  Cv={Cv:.5f}  samples={len(energies)}  time_beta={t1-t0:.2f}s\")\n",
        "\n",
        "    total_time = time.time() - start_total\n",
        "    print(f\"Simulación completa en {total_time:.1f}s. N={N}, eq_sweeps={eq_sweeps}, meas_sweeps={meas_sweeps}\")\n",
        "    return np.array(betas_done), np.array(Cv_list)\n",
        "\n",
        "\n",
        "# Resultados\n",
        "\n",
        "def save_results(output_dir, betas, cv_values):\n",
        "\n",
        "    # crear carpeta si no existe\n",
        "    os.makedirs(output_dir, exist_ok=True)\n",
        "    # Guarda CSV con beta, Cv y grafica png.\n",
        "    csv_path = os.path.join(output_dir, \"cv_vs_beta.csv\")\n",
        "    png_path = os.path.join(output_dir, \"cv_vs_beta.png\")\n",
        "\n",
        "    # guardar CSV\n",
        "    with open(csv_path, \"w\", newline=\"\") as f:\n",
        "        writer = csv.writer(f)\n",
        "        writer.writerow([\"beta\", \"Cv\"])\n",
        "        for b, c in zip(betas, cv_values):\n",
        "            writer.writerow([f\"{b:.6f}\", f\"{c:.12f}\"])\n",
        "    print(f\"Resultados guardados en {csv_path}\")\n",
        "\n",
        "    # plot\n",
        "    plt.figure(figsize=(9,5))\n",
        "    plt.plot(betas, cv_values, marker=None)                  # trazo principal\n",
        "    plt.axvline(beta_crit_theory, linestyle=\"--\", linewidth=1.0)  # vertical beta teórico\n",
        "    # etiqueta cerca del pico (ajustable)\n",
        "    plt.text(beta_crit_theory + 0.005, max(cv_values) * 0.9, \"β crítico (teoría)\", fontsize=9)\n",
        "    plt.xlabel(\"Termodinámico β\")\n",
        "    plt.ylabel(\"Capacidad calorífica (Cv)\")\n",
        "    plt.title(f\"Cv(β) - Ising 2D Metropolis - N={N}\")\n",
        "    plt.grid(True)\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(png_path, dpi=200)\n",
        "    plt.savefig(\"1.b.pdf\")\n",
        "    #print(f\"Gráfica guardada en {png_path}\")\n",
        "    plt.close()\n",
        "\n",
        "\n",
        "# MAIN: ejecutar simulación y guardar resultados\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    # correr simulación\n",
        "    betas_arr, Cv_arr = run_simulation(N, J, beta_values, eq_sweeps, meas_sweeps, sample_interval)\n",
        "    # guardar resultados y graficar\n",
        "    save_results(output_dir, betas_arr, Cv_arr)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "c3ohuSLe1-TJ",
        "outputId": "2b401d27-2b1f-4c3f-d1ed-0ae56acf9cdb"
      },
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)\n",
            "Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (0.60.0)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.60.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (25.0)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.4)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)\n",
            "Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba) (0.43.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)\n",
            "[1/81] beta=0.100  Cv=0.01698  samples=80  time_beta=1.60s\n",
            "[6/81] beta=0.150  Cv=0.04148  samples=80  time_beta=0.02s\n",
            "[11/81] beta=0.200  Cv=0.11532  samples=80  time_beta=0.02s\n",
            "[16/81] beta=0.250  Cv=0.17106  samples=80  time_beta=0.02s\n",
            "[21/81] beta=0.300  Cv=0.20025  samples=80  time_beta=0.02s\n",
            "[26/81] beta=0.350  Cv=0.58466  samples=80  time_beta=0.02s\n",
            "[31/81] beta=0.400  Cv=0.98928  samples=80  time_beta=0.02s\n",
            "[36/81] beta=0.450  Cv=1.38983  samples=80  time_beta=0.02s\n",
            "[41/81] beta=0.500  Cv=0.62111  samples=80  time_beta=0.02s\n",
            "[46/81] beta=0.550  Cv=0.42259  samples=80  time_beta=0.02s\n",
            "[51/81] beta=0.600  Cv=0.33732  samples=80  time_beta=0.02s\n",
            "[56/81] beta=0.650  Cv=0.21661  samples=80  time_beta=0.03s\n",
            "[61/81] beta=0.700  Cv=0.20781  samples=80  time_beta=0.02s\n",
            "[66/81] beta=0.750  Cv=0.12695  samples=80  time_beta=0.04s\n",
            "[71/81] beta=0.800  Cv=0.07376  samples=80  time_beta=0.02s\n",
            "[76/81] beta=0.850  Cv=0.07037  samples=80  time_beta=0.01s\n",
            "[81/81] beta=0.900  Cv=0.03491  samples=80  time_beta=0.01s\n",
            "Simulación completa en 3.2s. N=20, eq_sweeps=200, meas_sweeps=400\n",
            "Resultados guardados en results_ising/cv_vs_beta.csv\n"
          ]
        }
      ]
    }
  ]
}