# -*- coding: utf-8 -*-
"""T5_p2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4QGp6dLZKEN-buHZDOIE_DodItstTmv
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy as sc
from scipy.integrate import solve_ivp
from numba import njit

tmax = 30
#vidas medias en dias
u239 = 0.01625
Np239 = 2.36
A = 1000
B =20
lU = np.log(2)/u239
lNp = np.log(2)/Np239
tmax = 30
t = np.linspace(0,tmax,1000)
Y0 =[10,10,10]

def decaimiento(t, Y):
  U,Np, Pu = Y
  dU = A-lU*U
  dNp = lU*U - lNp*Np
  dPu = lNp*Np - B*Pu
  return [dU, dNp, dPu]

def evento_equilibrio(t,Y, tol=1e-3):
    der = decaimiento(t, Y)
    rmagnitud = np.linalg.norm(der) / max(1.0, np.linalg.norm(Y))
    return rmagnitud - tol

evento_equilibrio.terminal = False
evento_equilibrio.direction =  0    #punto de inflexion

sol = solve_ivp(
    decaimiento, [0.0, tmax], Y0,
    method="RK45",
    events=evento_equilibrio,
    rtol=1e-9, atol=1e-12,
    max_step=0.01                 # paso máx ~ 14.4 min para capturar bien U-239
)

t  = sol.t
U  = sol.y[0]
Np = sol.y[1]
Pu = sol.y[2]
teq = sol.t_events[0][0] if (len(sol.t_events[0]) > 0) else None

fig, ax = plt.subplots(figsize=(7, 4))

ax.plot(t, U,  label='U(t)')
ax.plot(t, Np, label='Np(t)')
ax.plot(t, Pu, label='Pu(t)')

if teq is not None:
    ax.axvline(teq, color='k', ls='--', alpha=0.6,
               label=fr'≈ equilibrio @ t={teq:.2f} d')

ax.set_xlabel('t (días)')
ax.set_ylabel('cantidad')
ax.set_title('Punto 2.a')
ax.legend()

plt.tight_layout()
plt.savefig("2.a.pdf")

fig, axes = plt.subplots(3, 1, figsize=(8, 8), sharex=True)

# Lista de datos y etiquetas
isotopos = [("U(t)", U), ("Np(t)", Np), ("Pu(t)", Pu)]

for i, (label, data) in enumerate(isotopos):
    axes[i].plot(t, data, label=label)
    if teq is not None:
        axes[i].axvline(teq, color='k', ls='--', alpha=0.6,
                        label=fr'≈ equilibrio @ t={teq:.2f} d')
    axes[i].set_ylabel("cantidad")
    axes[i].set_title(label)
    axes[i].legend()
    axes[i].grid(True)

axes[-1].set_xlabel("t (días)")
fig.suptitle("Punto 2.a – Sistema determinista U→Np→Pu", fontsize=14)

plt.tight_layout()
plt.savefig("2.a.sep.pdf")

R = np.array([[1, 0, 0],
              [-1, 1, 0],
              [0, -1, 1],
              [0, 0, -1]])
t = 0
r_evol = []
U = 10
Np = 10
Pu = 10
Y = [U, Np, Pu]
for d in range(30):
    for _ in range(1000):
        T = np.array([A, lU*Y[0],lNp*Y[1], B*Y[2]])

        tau_new = np.random.exponential(1 / T.sum())
        r = np.random.choice(range(len(R)), p=T / T.sum())
        Y_new = Y + R[r]
        t_new = t + tau_new
        r_evol.append(Y_new)
        t = t_new
        Y = Y_new

r_evol = np.array(r_evol)

fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)

isotopos = ["U-239", "Np-239", "Pu-239"]

for i in range(3):
    axes[i].plot(r_evol[:, i])
    axes[i].set_ylabel(isotopos[i])
    axes[i].grid(True)

axes[-1].set_xlabel("Iteraciones")
fig.suptitle("Evolución de los Isótopos - Solución Estocástica", fontsize=14)
plt.tight_layout()
plt.savefig("2.b.pdf")

#d
N = 1000
cNp = 80
T = 30

#Montecarlo

import math, random

random.seed(30)


def sim_trayectoria(T, A, B, lU, lNp, thresh= cNp):
    t  = 0.0
    U  = 0
    Np = 0
    Pu = 0

    # Si ya inicia en >= thresh (no ocurre aquí), se podría marcar. De momento empieza en 0.
    alcanzado = (Pu >= thresh)

    while t < T and not alcanzado:
        a1 = A
        a2 = lU  * U
        a3 = lNp * Np
        a4 = B * Pu

        a0 = a1 + a2 + a3 + a4
        if a0 <= 0.0:
            break

        r1 = random.random()
        dt = -math.log(r1) / a0
        t  += dt
        if t > T:
            break

        r2 = random.random() * a0
        if r2 < a1:
            U += 1
        elif r2 < a1 + a2:
            if U > 0:
                U  -= 1
                Np += 1
        elif r2 < a1 + a2 + a3:
            if Np > 0:
                Np -= 1
                Pu += 1
        else:
            if Pu > 0:
                Pu -= 1

        # CONCENTRACION CRITICA
        if Pu >= thresh:
            alcanzado = True

    return alcanzado

k = 0
for _ in range(1000):
    if sim_trayectoria(T, A, B, lU, lNp, cNp):
        k += 1

p = k / 1000
#desv
desv = math.sqrt(p * (1.0 - p) / 1000)

from scipy.stats import norm

def wilson_interval(k, n, conf=0.95):
    if n == 0:
        return (0.0, 1.0)

    z = norm.ppf(1 - (1-conf)/2)
    pg = k / n
    denom = 1 + z**2/n
    centro = (pg + z**2/(2*n)) / denom
    mitad = z * ((pg*(1-pg) + z**2/(4*n))/n)**0.5 / denom
    return centro - mitad, centro + mitad
li, ls = wilson_interval(k, 1000)

#Bayes
from scipy.stats import beta
alpha = 1 + k
betaa  = 1 + (1000 -k)
media = beta.mean(alpha, betaa)
#intervalos de confianza
q025, q975 = beta.ppf([0.025, 0.975], alpha, betaa)

prob = lambda x: 100.0 * x
with open("2.d.txt", "w", encoding="utf-8") as f:
    f.write("=== Probabilidad de alcanzar Pu >= {thr} en T={T} días ===\n".format(thr=cNp, T=T))
    f.write("Trayectorias N = {N}, éxitos k = {k}\n".format(N=1000,k=k))
    f.write("\n[Frecuentista]\n")
    f.write("p = {:.4f}%\n".format(prob(p)))
    f.write("SE   = {:+.4f} puntos porcentuales\n".format(prob(desv)))
    f.write("IC 95% (Wilson) = [{:.4f}%, {:.4f}%]\n".format(prob(li), prob(ls)))
    f.write("\n[Bayesiano]")
    f.write("Media posterior = {:.4f}%\n".format(prob(media)))
    f.write("IC 95% (Beta, cuantiles) = [{:.4f}%, {:.4f}%]\n".format(prob(q025), prob(q975)))