# -*- coding: utf-8 -*-
"""Punto_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOWFYXo43MKZI-qHsIm22tN6CHAnWo6O
"""

!pip install py-pde

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from numba import njit
import pde

import numpy as np
import matplotlib.pyplot as plt


L    = 1      # dominio [0,L]x[0,L]
N    = 150
dx   = L / N
alpha, beta = 1e-4, 0.8e-2
T    = 40.0
BC   = 'periodic'

dt_diff = (dx*dx) / (4.0*max(alpha, beta))
dt = 0.2 * dt_diff
steps = int(np.ceil(T / dt))

# ruido
rng = np.random.default_rng(0)
u = 0.1 * rng.standard_normal((N, N))
v = 0.1 * rng.standard_normal((N, N))

#Laplace
def lap(A):
    mode = 'wrap' if BC == 'periodic' else 'edge'   # periodic=torus, neumann=reflejo
    P = np.pad(A, 1, mode=mode)
    return (P[:-2,1:-1] + P[2:,1:-1] + P[1:-1,:-2] + P[1:-1,2:] - 4.0*P[1:-1,1:-1]) / (dx*dx)

for n in range(steps):
    Lu, Lv = lap(u), lap(v)
    Fu = u - u**3 - v - 0.05
    Gv = 10.0*(u - v)
    u += dt * (alpha*Lu + Fu)
    v += dt * (beta *Lv + Gv)

titulo = ""
plt.figure(figsize=(6,6))
plt.imshow(u, origin='lower', cmap='bone', interpolation='bilinear')
plt.axis('off')
plt.title(f"{titulo}\nα={alpha}, β={beta}, L={L}, N={N}, T≈{T}, dt≈{dt:.2e}, BC={BC}", fontsize=9)
plt.text(0.02, 0.02, "F=u-u^3-v-0.05\nG=10(u-v)", color='w', fontsize=9,
         transform=plt.gca().transAxes,
         bbox=dict(boxstyle='round,pad=0.3', fc='black', alpha=0.5))
plt.tight_layout()
plt.savefig(f"2_{titulo}.png", dpi=200, bbox_inches='tight', pad_inches=0)
#plt.show()
plt.close()

import numpy as np
import matplotlib.pyplot as plt
from pde import PDE, FieldCollection, ScalarField, CartesianGrid

def run_simulation():

    alpha = 0.0028
    beta = 0.05
    F_str = "2.5*u - u**2 - v - 0.05"
    G_str = "4*(0.3*u - v)"

    eq = PDE(
        {
            "u": f"{alpha} * laplace(u) + ({F_str})",
            "v": f"{beta} * laplace(v) + ({G_str})",
        }
    )

    grid = CartesianGrid([[0, 3], [0, 3]], [200, 200])

    u = ScalarField.random_normal(grid, mean=0.5, std=0.1)
    v = ScalarField.random_normal(grid, mean=0.25, std=0.1)
    state = FieldCollection([u, v])


    sol = eq.solve(state, t_range=15, dt=0.0005, tracker=['progress'])

    pattern_description = "Patrón de Manchas"

    plt.figure(figsize=(8, 7))
    plt.imshow(sol.data[0], cmap='binary')
    plt.title(f"Patrón de Turing: {pattern_description}", fontsize=14, fontweight='bold')
    plt.colorbar(label="Concentration")


    plt.text(5, 195,
             f'$\\bf{{\\alpha}} = {alpha}$\n$\\bf{{\\beta}} = {beta}$',
             color='deepskyblue', fontsize=11, verticalalignment='bottom')

    plt.text(5, 5,
             f'$\\bf{{F(u,v)}} = {F_str}$\n$\\bf{{G(u,v)}} = {G_str}$',
             color='deepskyblue', fontsize=11, verticalalignment='top')

    #plt.show()
    plt.savefig(f"2_{pattern_description}.png", dpi=300)
    plt.close()

    return sol


run_simulation()

def run_simulation2():

    alpha = 0.00017
    beta = 0.07
    F_str = "1.3*u - u**3 - v/3 - 0.05"
    G_str = "3*(0.5*u - v)"

    eq = PDE(
        {
            "u": f"{alpha} * laplace(u) + ({F_str})",
            "v": f"{beta} * laplace(v) + ({G_str})",
        }
    )

    grid = CartesianGrid([[0, 3], [0, 3]], [200, 200])

    u = ScalarField.random_normal(grid, mean=0.5, std=0.1)
    v = ScalarField.random_normal(grid, mean=0.25, std=0.1)
    state = FieldCollection([u, v])


    sol = eq.solve(state, t_range=15, dt=0.0005, tracker=['progress'])

    pattern_description = "Patrón"

    plt.figure(figsize=(8, 7))
    plt.imshow(sol.data[0], cmap='binary')
    plt.title(f"Patrón de Turing: {pattern_description}", fontsize=14, fontweight='bold')
    plt.colorbar(label="Concentration")


    plt.text(5, 195,
             f'$\\bf{{\\alpha}} = {alpha}$\n$\\bf{{\\beta}} = {beta}$',
             color='deepskyblue', fontsize=11, verticalalignment='bottom')

    plt.text(5, 5,
             f'$\\bf{{F(u,v)}} = {F_str}$\n$\\bf{{G(u,v)}} = {G_str}$',
             color='deepskyblue', fontsize=11, verticalalignment='top')

    #plt.show()
    plt.savefig(f"2_{pattern_description}.png", dpi=300)
    plt.close()
    return sol

run_simulation2()

