# -*- coding: utf-8 -*-
"""Punto_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_QwHA8qNxUqKPK3SKyP0UCLT8QSXIOQ
"""

!pip install py-pde

#1a
# Oscilador Armonico Simulación  (V(x) = -x^2/50) con Crank–Nicolson + Neumann.Genera frames PNG y los convierte en animation.mp4 usando ffmpeg.


import os
import time
import shutil
import subprocess
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse
from scipy.sparse.linalg import splu


# Parámetros

alpha = 0.1                # del enunciado (controla término cinético)
x_min, x_max = -20.0, 20.0
Nx = 801                   # número de puntos espaciales
x = np.linspace(x_min, x_max, Nx)
dx = x[1] - x[0]

t_final = 150.0            # tiempo final
dt = 0.01                  # paso temporal
Nt = int(np.round(t_final / dt))

# Modo preview para pruebas rápidas
preview = False
if preview:
    print("[INFO] MODO PREVIEW activado: pasos reducidos")
    Nt = 200
    t_final = Nt * dt

print(f"[INFO] Nx={Nx}, dx={dx:.4f}, dt={dt}, Nt={Nt}, t_final={t_final}")


# Potencial y condición inicial

def V_harmonico(x):
    return x**2 / 50.0

V = V_harmonico(x)

# Paquete gaussiano desplazado con fase
x0 = 10.0
k0 = 2.0
def psi0(x):
    return np.exp(-2.0 * (x - x0)**2) * np.exp(-1j * k0 * x)

psi = psi0(x)

# normalizar numéricamente: ∫ |ψ|^2 dx = 1
norm = np.sqrt(np.sum(np.abs(psi)**2) * dx)
psi /= norm


# Laplaciana con condiciones de Neumann

diag = np.full(Nx, -2.0) / dx**2
off  = np.full(Nx-1, 1.0) / dx**2
L = sparse.diags([off, diag, off], offsets=[-1,0,1], format='lil')

# ajustar extremos para Neumann
L[0,:] = 0.0
L[0,0] = -2.0/dx**2
L[0,1] = 2.0/dx**2
L[-1,:] = 0.0
L[-1,-1] = -2.0/dx**2
L[-1,-2] = 2.0/dx**2

L = L.tocsc()
V_diag = sparse.diags(V, 0, format='csc')
H = -alpha * L + V_diag


# Crank–Nicolson matrices A and B
# (I + i dt/2 H) ψ^{n+1} = (I - i dt/2 H) ψ^n

I = sparse.identity(Nx, format='csc')
A = I + 1j * dt / 2.0 * H
B = I - 1j * dt / 2.0 * H

# LU factorization de A para resolver cada paso
t0 = time.time()
A_factor = splu(A)
t1 = time.time()
print(f"[INFO] Factorización LU completada en {t1 - t0:.3f} s")


# Observables: <x> y sigma

def expectation_x(psi, x):
    return np.sum(x * (np.abs(psi)**2)) * dx

def expectation_x2(psi, x):
    return np.sum((x**2) * (np.abs(psi)**2)) * dx


# Bucle temporal, guardado de snapshots

times = np.linspace(0, t_final, Nt+1)
mu_t = np.zeros(Nt+1, dtype=float)
sigma_t = np.zeros(Nt+1, dtype=float)

mu_t[0] = expectation_x(psi, x)
sigma_t[0] = np.sqrt(max(0.0, expectation_x2(psi, x) - mu_t[0]**2))

psi_n = psi.copy()

# decidir cuántos snapshots aprox queremos (300 por defecto para buena animación)
target_snapshots = 300 if not preview else 60
save_every = max(1, Nt // target_snapshots)
print(f"[INFO] Guardando snapshots cada {save_every} pasos ≈ {target_snapshots} snapshots")

snapshots = []
snapshot_times = []

t_start = time.time()
for n in range(1, Nt+1):
    # right-hand side
    b = B.dot(psi_n)
    # resolver A ψ^{n+1} = b
    psi_np1 = A_factor.solve(b)
    # renormalizar para controlar errores numéricos
    psi_np1 /= np.sqrt(np.sum(np.abs(psi_np1)**2) * dx)
    psi_n = psi_np1

    mu_t[n] = expectation_x(psi_n, x)
    sigma_t[n] = np.sqrt(max(0.0, expectation_x2(psi_n, x) - mu_t[n]**2))

    if (n % save_every == 0) or (n == Nt):
        snapshots.append(psi_n.copy())
        snapshot_times.append(n * dt)
t_end = time.time()
print(f"[INFO] Evolución completada en {t_end - t_start:.1f} s, snapshots: {len(snapshots)}")


# Preparar frames con matplotlib (fijas escalas para evitar saltos)

frames_dir = "frames"
if os.path.exists(frames_dir):
    print(f"[INFO] Limpiando directorio existente {frames_dir}")
    shutil.rmtree(frames_dir)
os.makedirs(frames_dir, exist_ok=True)

# Preparar figura y ejes
fig, axs = plt.subplots(2, 1, figsize=(10, 8), constrained_layout=True)

# Normalizaciones y límites fijos para consistencia visual
prob_max = np.max(np.abs(snapshots[0])**2) * 1.2  # límite y escala para densidad
if np.max(np.abs(V)) > 0:
    V_scaled = V / np.max(np.abs(V)) * prob_max
else:
    V_scaled = np.zeros_like(V)

axs[0].set_xlim(x_min, x_max)
axs[0].set_ylim(0.0, prob_max)
axs[0].set_xlabel("x")
axs[0].set_ylabel(r"$|\psi(x,t)|^2$")
axs[0].plot(x, V_scaled, 'k--', linewidth=1.0, label="V(x) escalado")
axs[0].legend()
axs[0].set_title("Evolución de la densidad de probabilidad")

axs[1].set_xlim(0.0, t_final)
# definir límites verticales de la banda usando mu_t y sigma_t
mu_min = np.min(mu_t) if np.any(mu_t) else -10.0
mu_max = np.max(mu_t) if np.any(mu_t) else 10.0
sigma_max = np.max(sigma_t) if np.any(sigma_t) else 1.0
axs[1].set_ylim(mu_min - 2*sigma_max, mu_max + 2*sigma_max)
axs[1].set_xlabel("t")
axs[1].set_ylabel(r"$\langle x\rangle$ y $\sigma$")
axs[1].set_title("Posición esperada y banda de incertidumbre")

# pre-dibujar (vacío) la línea de mu para actualizar después
line_mu, = axs[1].plot([], [], color='C1', lw=1.5, label=r'$\mu(t)$')
axs[1].legend()


# Generar y guardar frames PNG (limpiando correctamente las líneas y colecciones previas)

print("[INFO] Generando frames PNG...")
for i, (psi_snap, t_snap) in enumerate(zip(snapshots, snapshot_times)):


    while len(axs[0].lines) > 1:
        axs[0].lines[-1].remove()   #  Limpieza de trazados previos

    # eliminar colecciones (fill_between) anteriores en axs[1] correctamente:
    prev_collections = list(axs[1].collections)
    for coll in prev_collections:
        try:
            coll.remove()
        except Exception:
            # en caso de que no se pueda remover, ignoramos y seguimos
            pass

    # eliminar líneas
    prev_lines = list(axs[1].lines)
    for ln in prev_lines:

        try:
            ln.remove()
        except Exception:
            pass

    # panel 0: densidad de probabilidad actual
    axs[0].plot(x, np.abs(psi_snap)**2, color='C0', lw=1.2)

    # panel 1: rellenar la banda mu ± sigma hasta el tiempo actual y trazar mu(t)
    t_idx = int(np.searchsorted(times, t_snap))
    # evitar índices fuera de rango
    t_idx = min(t_idx, len(times) - 1)
    axs[1].fill_between(times[:t_idx+1], mu_t[:t_idx+1] - sigma_t[:t_idx+1], mu_t[:t_idx+1] + sigma_t[:t_idx+1], alpha=0.3)
    axs[1].plot(times[:t_idx+1], mu_t[:t_idx+1], color='C1', lw=1.5)

    # anotación con el tiempo actual
    text_time = axs[0].text(0.02, 0.92, f"t = {t_snap:.2f}", transform=axs[0].transAxes, fontsize=10,
                             bbox=dict(facecolor='white', alpha=0.6, edgecolor='none'))

    # guardar frame
    frame_filename = os.path.join(frames_dir, f"frame_{i:04d}.png")
    plt.savefig(frame_filename, dpi=150)
    # remover la anotación para no acumularla
    text_time.remove()

print(f"[INFO] Frames guardados en {frames_dir} (total {len(snapshots)})")


# ffmpeg para crear animation.mp4

fps = 20
output_mp4 = "1.a.mp4"

ffmpeg_cmd = [
    "ffmpeg",
    "-y",  # overwrite
    "-framerate", str(fps),
    "-i", os.path.join(frames_dir, "frame_%04d.png"),
    "-c:v", "libx264",
    "-pix_fmt", "yuv420p",
    "-crf", "18",
    output_mp4
]

print("[INFO] Ejecutando ffmpeg para crear el video...")
print("Comando:", " ".join(ffmpeg_cmd))
try:
    subprocess.run(ffmpeg_cmd, check=True)
    print(f"[INFO] Video creado: {output_mp4}")
except FileNotFoundError:
    print("[ERROR] ffmpeg no encontrado: instala ffmpeg (ej. apt install ffmpeg) o añade ffmpeg a PATH.")
except subprocess.CalledProcessError as e:
    print("[ERROR] ffmpeg falló:", e)


# Limpieza de frames

cleanup_frames = True
if cleanup_frames:
    try:
        shutil.rmtree(frames_dir)
        print(f"[INFO] Frames temporales eliminados: {frames_dir}")
    except Exception as e:
        print("[WARNING] No se pudieron eliminar frames:", e)

print("[DONE]")

#1b Oscilador cuartico Simulación del oscilador cuártico V(x)=(x/5)^4 con Crank–Nicolson + Neumann BC.


import os
import time
import shutil
import subprocess
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse
from scipy.sparse.linalg import splu


# Parámetros

alpha = 0.1
x_min, x_max = -20.0, 20.0
Nx = 801
x = np.linspace(x_min, x_max, Nx)
dx = x[1] - x[0]

t_final = 50.0    # Enunciado pide t = 50
dt = 0.01
Nt = int(np.round(t_final / dt))

# Modo preview para pruebas rápidas
preview = False
if preview:
    print("[INFO] PREVIEW mode ON (reduced steps)")
    Nt = 200
    t_final = Nt * dt

print(f"[INFO] Nx={Nx}, dx={dx:.4f}, dt={dt}, Nt={Nt}, t_final={t_final}")


# Potencial cuártico y condición inicial

def V_cuartico(x):
    return (x / 5.0) ** 4

V = V_cuartico(x)

x0 = 10.0
k0 = 2.0
def psi0(x):
    return np.exp(-2.0 * (x - x0)**2) * np.exp(-1j * k0 * x)

psi = psi0(x)

psi /= np.sqrt(np.sum(np.abs(psi)**2) * dx)


# Laplaciana con Neumann

diag = np.full(Nx, -2.0) / dx**2
off  = np.full(Nx-1, 1.0) / dx**2
L = sparse.diags([off, diag, off], offsets=[-1,0,1], format='lil')

# Extremos Neumann
L[0,:] = 0.0
L[0,0] = -2.0/dx**2
L[0,1] = 2.0/dx**2
L[-1,:] = 0.0
L[-1,-1] = -2.0/dx**2
L[-1,-2] = 2.0/dx**2

L = L.tocsc()
V_diag = sparse.diags(V, 0, format='csc')
H = -alpha * L + V_diag


# Crank–Nicolson matrices

I = sparse.identity(Nx, format='csc')
A = I + 1j * dt / 2.0 * H
B = I - 1j * dt / 2.0 * H

t0 = time.time()
A_factor = splu(A)
t1 = time.time()
print(f"[INFO] LU factorization done in {t1-t0:.3f} s")


# Observables

def expectation_x(psi, x):
    return np.sum(x * (np.abs(psi)**2)) * dx

def expectation_x2(psi, x):
    return np.sum((x**2) * (np.abs(psi)**2)) * dx

times = np.linspace(0, t_final, Nt+1)
mu_t = np.zeros(Nt+1)
sigma_t = np.zeros(Nt+1)
mu_t[0] = expectation_x(psi, x)
sigma_t[0] = np.sqrt(max(0.0, expectation_x2(psi, x) - mu_t[0]**2))

psi_n = psi.copy()
save_every = max(1, Nt // 300)  # approx 300 snapshots for smooth animation
snapshots = []
snapshot_times = []

print("[INFO] Starting time evolution for quartic oscillator...")
tstart = time.time()
for n in range(1, Nt+1):
    b = B.dot(psi_n)
    psi_np1 = A_factor.solve(b)
    psi_np1 /= np.sqrt(np.sum(np.abs(psi_np1)**2) * dx)
    psi_n = psi_np1
    mu_t[n] = expectation_x(psi_n, x)
    sigma_t[n] = np.sqrt(max(0.0, expectation_x2(psi_n, x) - mu_t[n]**2))
    if (n % save_every == 0) or (n == Nt):
        snapshots.append(psi_n.copy())
        snapshot_times.append(n * dt)
tend = time.time()
print(f"[INFO] Evolution finished in {tend - tstart:.1f} s, snapshots: {len(snapshots)}")


# Preparar frames y figura

frames_dir = "frames_cuartico"
if os.path.exists(frames_dir):
    print(f"[INFO] Cleaning existing {frames_dir}")
    shutil.rmtree(frames_dir)
os.makedirs(frames_dir, exist_ok=True)

fig, axs = plt.subplots(2,1, figsize=(10,8), constrained_layout=True)

# escalas fijas
prob_max = np.max(np.abs(snapshots[0])**2) * 1.2
V_scaled = V / np.max(np.abs(V)) * prob_max if np.max(np.abs(V)) > 0 else np.zeros_like(V)

axs[0].set_xlim(x_min, x_max)
axs[0].set_ylim(0.0, prob_max)
axs[0].set_xlabel("x")
axs[0].set_ylabel(r"$|\psi(x,t)|^2$")
axs[0].plot(x, V_scaled, 'k--', linewidth=1.0, label="V(x) escalado")
axs[0].legend()
axs[0].set_title("Densidad de probabilidad - Oscilador cuártico")

axs[1].set_xlim(0.0, t_final)
mu_min = np.min(mu_t) if np.any(mu_t) else -10.0
mu_max = np.max(mu_t) if np.any(mu_t) else 10.0
sigma_max = np.max(sigma_t) if np.any(sigma_t) else 1.0
axs[1].set_ylim(mu_min - 2*sigma_max, mu_max + 2*sigma_max)
axs[1].set_xlabel("t")
axs[1].set_ylabel(r"$\langle x\rangle$ y $\sigma$")
axs[1].set_title("Posición esperada y banda de incertidumbre")

# placeholder line
placeholder_line, = axs[1].plot([], [], color='C1', lw=1.5, label=r'$\mu(t)$')
axs[1].legend()


# Guardar frames PNG

print("[INFO] Generating PNG frames...")
for i, (psi_snap, t_snap) in enumerate(zip(snapshots, snapshot_times)):

    while len(axs[0].lines) > 1:
        axs[0].lines[-1].remove()


    prev_collections = list(axs[1].collections)
    for coll in prev_collections:
        try:
            coll.remove()
        except Exception:
            pass

    # remover líneas previas en axs
    prev_lines = list(axs[1].lines)
    for ln in prev_lines:
        try:
            ln.remove()
        except Exception:
            pass

    # dibujar densidad en axs[0]
    axs[0].plot(x, np.abs(psi_snap)**2, color='C0', lw=1.2)

    # dibujar banda y mu hasta t_snap en axs[1]
    t_idx = int(np.searchsorted(times, t_snap))
    t_idx = min(t_idx, len(times)-1)
    axs[1].fill_between(times[:t_idx+1], mu_t[:t_idx+1] - sigma_t[:t_idx+1], mu_t[:t_idx+1] + sigma_t[:t_idx+1], alpha=0.3)
    axs[1].plot(times[:t_idx+1], mu_t[:t_idx+1], color='C1', lw=1.5)

    # anotación temporal
    text_time = axs[0].text(0.02, 0.92, f"t = {t_snap:.2f}", transform=axs[0].transAxes, fontsize=10,
                             bbox=dict(facecolor='white', alpha=0.6, edgecolor='none'))

    frame_filename = os.path.join(frames_dir, f"frame_{i:04d}.png")
    plt.savefig(frame_filename, dpi=150)
    text_time.remove()

print(f"[INFO] Saved frames in {frames_dir} ({len(snapshots)} images)")


# ffmpeg -> mp4

fps = 20
output_mp4 = "1.b.mp4"
ffmpeg_cmd = [
    "ffmpeg",
    "-y",
    "-framerate", str(fps),
    "-i", os.path.join(frames_dir, "frame_%04d.png"),
    "-c:v", "libx264",
    "-pix_fmt", "yuv420p",
    "-crf", "18",
    output_mp4
]

print("[INFO] Running ffmpeg to create video...")
try:
    subprocess.run(ffmpeg_cmd, check=True)
    print(f"[INFO] Video created: {output_mp4}")
except FileNotFoundError:
    print("[ERROR] ffmpeg not found. Install ffmpeg (e.g. apt install ffmpeg) or add to PATH.")
except subprocess.CalledProcessError as e:
    print("[ERROR] ffmpeg failed:", e)


# Limpiar frames temporales

cleanup_frames = True
if cleanup_frames:
    try:
        shutil.rmtree(frames_dir)
        print(f"[INFO] Removed frames directory: {frames_dir}")
    except Exception as e:
        print("[WARNING] Could not remove frames dir:", e)

print("[DONE]")

#1c sombrero Simulación del potencial "sombrero" V(x) = (1/50) * (x^4/100 - x^2) Usa Crank–Nicolson + condiciones de frontera Neumann.

import os
import time
import shutil
import subprocess
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse
from scipy.sparse.linalg import splu


# Parámetros

alpha = 0.1
x_min, x_max = -20.0, 20.0
Nx = 801
x = np.linspace(x_min, x_max, Nx)
dx = x[1] - x[0]

t_final = 150.0
dt = 0.01
Nt = int(np.round(t_final / dt))

# Opcional: modo preview para pruebas rápidas
preview = False
if preview:
    print("[INFO] PREVIEW ON: pasos reducidos")
    Nt = 200
    t_final = Nt * dt

print(f"[INFO] Nx={Nx}, dx={dx:.4f}, dt={dt}, Nt={Nt}, t_final={t_final}")


# Potencial sombrero e inicial

def V_sombrero(x):
    return (1.0/50.0) * ((x**4) / 100.0 - x**2)

V = V_sombrero(x)

x0 = 10.0
k0 = 2.0
def psi0(x):
    return np.exp(-2.0 * (x - x0)**2) * np.exp(-1j * k0 * x)

psi = psi0(x)
psi /= np.sqrt(np.sum(np.abs(psi)**2) * dx)   # normalizar


# Laplaciana Neumann

diag = np.full(Nx, -2.0) / dx**2
off  = np.full(Nx-1, 1.0) / dx**2
L = sparse.diags([off, diag, off], offsets=[-1,0,1], format='lil')

# ajustar extremos para Neumann
L[0,:] = 0.0
L[0,0] = -2.0/dx**2
L[0,1] = 2.0/dx**2
L[-1,:] = 0.0
L[-1,-1] = -2.0/dx**2
L[-1,-2] = 2.0/dx**2

L = L.tocsc()
V_diag = sparse.diags(V, 0, format='csc')
H = -alpha * L + V_diag


# Crank–Nicolson matrices

I = sparse.identity(Nx, format='csc')
A = I + 1j * dt / 2.0 * H
B = I - 1j * dt / 2.0 * H

t0 = time.time()
A_factor = splu(A)
t1 = time.time()
print(f"[INFO] LU factorization done in {t1 - t0:.3f} s")


# Observables

def expectation_x(psi, x):
    return np.sum(x * (np.abs(psi)**2)) * dx

def expectation_x2(psi, x):
    return np.sum((x**2) * (np.abs(psi)**2)) * dx

times = np.linspace(0, t_final, Nt+1)
mu_t = np.zeros(Nt+1)
sigma_t = np.zeros(Nt+1)
mu_t[0] = expectation_x(psi, x)
sigma_t[0] = np.sqrt(max(0.0, expectation_x2(psi, x) - mu_t[0]**2))

psi_n = psi.copy()
# número de snapshots objetivo para animación
target_snapshots = 300 if not preview else 60
save_every = max(1, Nt // target_snapshots)
snapshots = []
snapshot_times = []


# Evolución temporal y almacenamiento de snapshots

print("[INFO] Starting time evolution for sombrero potential...")
t_start = time.time()
for n in range(1, Nt+1):
    b = B.dot(psi_n)
    psi_np1 = A_factor.solve(b)
    psi_np1 /= np.sqrt(np.sum(np.abs(psi_np1)**2) * dx)  # renormalizar
    psi_n = psi_np1

    mu_t[n] = expectation_x(psi_n, x)
    sigma_t[n] = np.sqrt(max(0.0, expectation_x2(psi_n, x) - mu_t[n]**2))

    if (n % save_every == 0) or (n == Nt):
        snapshots.append(psi_n.copy())
        snapshot_times.append(n * dt)
t_end = time.time()
print(f"[INFO] Evolution finished in {t_end - t_start:.1f} s, snapshots: {len(snapshots)}")


# Preparar frames (matplotlib) con límites fijos

frames_dir = "frames_sombrero"
if os.path.exists(frames_dir):
    print(f"[INFO] Removing existing frames dir {frames_dir}")
    shutil.rmtree(frames_dir)
os.makedirs(frames_dir, exist_ok=True)

fig, axs = plt.subplots(2, 1, figsize=(10, 8), constrained_layout=True)

# Escalas fijas para evitar saltos en la animación
prob_max = np.max(np.abs(snapshots[0])**2) * 1.2
V_scaled = V / np.max(np.abs(V)) * prob_max if np.max(np.abs(V)) > 0 else np.zeros_like(V)

axs[0].set_xlim(x_min, x_max)
axs[0].set_ylim(0.0, prob_max)
axs[0].set_xlabel("x")
axs[0].set_ylabel(r"$|\psi(x,t)|^2$")
axs[0].plot(x, V_scaled, 'k--', linewidth=1.0, label="V(x) escalado")
axs[0].legend()
axs[0].set_title("Densidad de probabilidad - Potencial Sombrero")

axs[1].set_xlim(0.0, t_final)
mu_min = np.min(mu_t) if np.any(mu_t) else -10.0
mu_max = np.max(mu_t) if np.any(mu_t) else 10.0
sigma_max = np.max(sigma_t) if np.any(sigma_t) else 1.0
axs[1].set_ylim(mu_min - 2*sigma_max, mu_max + 2*sigma_max)
axs[1].set_xlabel("t")
axs[1].set_ylabel(r"$\langle x\rangle$ y $\sigma$")
axs[1].set_title("Posición esperada y banda de incertidumbre")


placeholder_line, = axs[1].plot([], [], color='C1', lw=1.5, label=r'$\mu(t)$')
axs[1].legend()


# Generar y guardar frames PNG

print("[INFO] Generating PNG frames...")
for i, (psi_snap, t_snap) in enumerate(zip(snapshots, snapshot_times)):

    while len(axs[0].lines) > 1:
        axs[0].lines[-1].remove()


    prev_collections = list(axs[1].collections)
    for coll in prev_collections:
        try:
            coll.remove()
        except Exception:
            pass

    # remover líneas previas en axs[1]
    prev_lines = list(axs[1].lines)
    for ln in prev_lines:
        try:
            ln.remove()
        except Exception:
            pass


    axs[0].plot(x, np.abs(psi_snap)**2, color='C0', lw=1.2)

    # panel 1: banda y mu hasta t_snap
    t_idx = int(np.searchsorted(times, t_snap))
    t_idx = min(t_idx, len(times)-1)
    axs[1].fill_between(times[:t_idx+1], mu_t[:t_idx+1] - sigma_t[:t_idx+1], mu_t[:t_idx+1] + sigma_t[:t_idx+1], alpha=0.3)
    axs[1].plot(times[:t_idx+1], mu_t[:t_idx+1], color='C1', lw=1.5)

    # anotación temporal
    text_time = axs[0].text(0.02, 0.92, f"t = {t_snap:.2f}", transform=axs[0].transAxes, fontsize=10,
                             bbox=dict(facecolor='white', alpha=0.6, edgecolor='none'))

    # guardar frame
    frame_filename = os.path.join(frames_dir, f"frame_{i:04d}.png")
    plt.savefig(frame_filename, dpi=150)
    # quitar anotación para siguiente frame
    text_time.remove()

print(f"[INFO] Frames saved in {frames_dir} ({len(snapshots)} images)")


# ffmpeg para .mp4

fps = 20
output_mp4 = "1.c.mp4"
ffmpeg_cmd = [
    "ffmpeg",
    "-y",  # overwrite
    "-framerate", str(fps),
    "-i", os.path.join(frames_dir, "frame_%04d.png"),
    "-c:v", "libx264",
    "-pix_fmt", "yuv420p",
    "-crf", "18",
    output_mp4
]

print("[INFO] Running ffmpeg to create video...")
try:
    subprocess.run(ffmpeg_cmd, check=True)
    print(f"[INFO] Video created: {output_mp4}")
except FileNotFoundError:
    print("[ERROR] ffmpeg not found. Install ffmpeg (e.g. apt install ffmpeg) or add to PATH.")
except subprocess.CalledProcessError as e:
    print("[ERROR] ffmpeg failed:", e)


# Limpieza de frames temporales (opcional)

cleanup_frames = True
if cleanup_frames:
    try:
        shutil.rmtree(frames_dir)
        print(f"[INFO] Removed frames directory: {frames_dir}")
    except Exception as e:
        print("[WARNING] Could not remove frames dir:", e)

print("[DONE]")

