{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "d5307aef34cb4a05ac75b67bceae74e5": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_412b0d94034943c083ae8aacf58eab91",
              "IPY_MODEL_57f8f46259854e889ece5cb50f022c13",
              "IPY_MODEL_45d9cf8618d24e9c82d9d7eb7ba12788"
            ],
            "layout": "IPY_MODEL_719b2e552dbc463baa27692fb84b2058"
          }
        },
        "412b0d94034943c083ae8aacf58eab91": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_d85aed09dc59461eb372563df82e057b",
            "placeholder": "​",
            "style": "IPY_MODEL_f2bbd9d3e40d40268351cbfd16973086",
            "value": "100%"
          }
        },
        "57f8f46259854e889ece5cb50f022c13": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_c30cd1c004f540be90d791f951f8f9b0",
            "max": 15,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_af3b27f0a97b4bdab2460751eea65e0a",
            "value": 15
          }
        },
        "45d9cf8618d24e9c82d9d7eb7ba12788": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_b02c67e500f945e3b11695212fb093e4",
            "placeholder": "​",
            "style": "IPY_MODEL_aa772dc511544eea8a730b24fa2acbc7",
            "value": " 15.0/15.0 [00:50&lt;00:00,  3.34s/it]"
          }
        },
        "719b2e552dbc463baa27692fb84b2058": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "d85aed09dc59461eb372563df82e057b": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "f2bbd9d3e40d40268351cbfd16973086": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "c30cd1c004f540be90d791f951f8f9b0": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "af3b27f0a97b4bdab2460751eea65e0a": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": null,
            "description_width": ""
          }
        },
        "b02c67e500f945e3b11695212fb093e4": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "aa772dc511544eea8a730b24fa2acbc7": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "f2d74260e9ec42a598305d2299a44943": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_040dcb4028104032b97c38e0e4ff1808",
              "IPY_MODEL_aaf028446b4249e5be7d4cfe28b1d369",
              "IPY_MODEL_d3aeb127033d408da3b3f89f542e6379"
            ],
            "layout": "IPY_MODEL_4dcf24d08c094343bad2e7f7deb4e996"
          }
        },
        "040dcb4028104032b97c38e0e4ff1808": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_a5200e2f0f0b4cd9b96ab844d43b54ea",
            "placeholder": "​",
            "style": "IPY_MODEL_2b37a2977ecb4881b60a2eceb87959e7",
            "value": "100%"
          }
        },
        "aaf028446b4249e5be7d4cfe28b1d369": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_eafb64e439fa48fda7ab4631b71300f5",
            "max": 15,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_2869642605d644de97ea595ad163888c",
            "value": 15
          }
        },
        "d3aeb127033d408da3b3f89f542e6379": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_78a1ce26e5544bc885e90810010311bc",
            "placeholder": "​",
            "style": "IPY_MODEL_0c92d74a90b5488aa84619b3bb4488db",
            "value": " 15.0/15.0 [00:46&lt;00:00,  3.08s/it]"
          }
        },
        "4dcf24d08c094343bad2e7f7deb4e996": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "a5200e2f0f0b4cd9b96ab844d43b54ea": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "2b37a2977ecb4881b60a2eceb87959e7": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "eafb64e439fa48fda7ab4631b71300f5": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "2869642605d644de97ea595ad163888c": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": null,
            "description_width": ""
          }
        },
        "78a1ce26e5544bc885e90810010311bc": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "0c92d74a90b5488aa84619b3bb4488db": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/mcramireza1/Grupo7_Metodos2/blob/main/T4/Punto_2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install py-pde"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "jf9TIR595DAn",
        "outputId": "28f1177a-55ef-45be-a92e-3be437f6a737"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: py-pde in /usr/local/lib/python3.12/dist-packages (0.46.0)\n",
            "Requirement already satisfied: matplotlib>=3.1 in /usr/local/lib/python3.12/dist-packages (from py-pde) (3.10.0)\n",
            "Requirement already satisfied: numba>=0.59 in /usr/local/lib/python3.12/dist-packages (from py-pde) (0.60.0)\n",
            "Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.12/dist-packages (from py-pde) (2.0.2)\n",
            "Requirement already satisfied: scipy>=1.10 in /usr/local/lib/python3.12/dist-packages (from py-pde) (1.16.2)\n",
            "Requirement already satisfied: sympy>=1.9 in /usr/local/lib/python3.12/dist-packages (from py-pde) (1.13.3)\n",
            "Requirement already satisfied: tqdm>=4.66 in /usr/local/lib/python3.12/dist-packages (from py-pde) (4.67.1)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (4.60.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (1.4.9)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (25.0)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (3.2.4)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (2.9.0.post0)\n",
            "Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.59->py-pde) (0.43.0)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.9->py-pde) (1.3.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1->py-pde) (1.17.0)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "GTvQixrB4kFH"
      },
      "outputs": [],
      "source": [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib as mpl\n",
        "from numba import njit\n",
        "import pde\n",
        "\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "\n",
        "L    = 1      # dominio [0,L]x[0,L]\n",
        "N    = 150\n",
        "dx   = L / N\n",
        "alpha, beta = 1e-4, 0.8e-2\n",
        "T    = 40.0\n",
        "BC   = 'periodic'\n",
        "\n",
        "dt_diff = (dx*dx) / (4.0*max(alpha, beta))\n",
        "dt = 0.2 * dt_diff\n",
        "steps = int(np.ceil(T / dt))\n",
        "\n",
        "# ruido\n",
        "rng = np.random.default_rng(0)\n",
        "u = 0.1 * rng.standard_normal((N, N))\n",
        "v = 0.1 * rng.standard_normal((N, N))\n",
        "\n",
        "#Laplace\n",
        "def lap(A):\n",
        "    mode = 'wrap' if BC == 'periodic' else 'edge'   # periodic=torus, neumann=reflejo\n",
        "    P = np.pad(A, 1, mode=mode)\n",
        "    return (P[:-2,1:-1] + P[2:,1:-1] + P[1:-1,:-2] + P[1:-1,2:] - 4.0*P[1:-1,1:-1]) / (dx*dx)\n",
        "\n",
        "for n in range(steps):\n",
        "    Lu, Lv = lap(u), lap(v)\n",
        "    Fu = u - u**3 - v - 0.05\n",
        "    Gv = 10.0*(u - v)\n",
        "    u += dt * (alpha*Lu + Fu)\n",
        "    v += dt * (beta *Lv + Gv)\n",
        "\n",
        "titulo = \"\"\n",
        "plt.figure(figsize=(6,6))\n",
        "plt.imshow(u, origin='lower', cmap='bone', interpolation='bilinear')\n",
        "plt.axis('off')\n",
        "plt.title(f\"{titulo}\\nα={alpha}, β={beta}, L={L}, N={N}, T≈{T}, dt≈{dt:.2e}, BC={BC}\", fontsize=9)\n",
        "plt.text(0.02, 0.02, \"F=u-u^3-v-0.05\\nG=10(u-v)\", color='w', fontsize=9,\n",
        "         transform=plt.gca().transAxes,\n",
        "         bbox=dict(boxstyle='round,pad=0.3', fc='black', alpha=0.5))\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"2_{titulo}.png\", dpi=200, bbox_inches='tight', pad_inches=0)\n",
        "#plt.show()\n",
        "plt.close()\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from pde import PDE, FieldCollection, ScalarField, CartesianGrid\n",
        "\n",
        "def run_simulation():\n",
        "\n",
        "    alpha = 0.0028\n",
        "    beta = 0.05\n",
        "    F_str = \"2.5*u - u**2 - v - 0.05\"\n",
        "    G_str = \"4*(0.3*u - v)\"\n",
        "\n",
        "    eq = PDE(\n",
        "        {\n",
        "            \"u\": f\"{alpha} * laplace(u) + ({F_str})\",\n",
        "            \"v\": f\"{beta} * laplace(v) + ({G_str})\",\n",
        "        }\n",
        "    )\n",
        "\n",
        "    grid = CartesianGrid([[0, 3], [0, 3]], [200, 200])\n",
        "\n",
        "    u = ScalarField.random_normal(grid, mean=0.5, std=0.1)\n",
        "    v = ScalarField.random_normal(grid, mean=0.25, std=0.1)\n",
        "    state = FieldCollection([u, v])\n",
        "\n",
        "\n",
        "    sol = eq.solve(state, t_range=15, dt=0.0005, tracker=['progress'])\n",
        "\n",
        "    pattern_description = \"Patrón de Manchas\"\n",
        "\n",
        "    plt.figure(figsize=(8, 7))\n",
        "    plt.imshow(sol.data[0], cmap='binary')\n",
        "    plt.title(f\"Patrón de Turing: {pattern_description}\", fontsize=14, fontweight='bold')\n",
        "    plt.colorbar(label=\"Concentration\")\n",
        "\n",
        "\n",
        "    plt.text(5, 195,\n",
        "             f'$\\\\bf{{\\\\alpha}} = {alpha}$\\n$\\\\bf{{\\\\beta}} = {beta}$',\n",
        "             color='deepskyblue', fontsize=11, verticalalignment='bottom')\n",
        "\n",
        "    plt.text(5, 5,\n",
        "             f'$\\\\bf{{F(u,v)}} = {F_str}$\\n$\\\\bf{{G(u,v)}} = {G_str}$',\n",
        "             color='deepskyblue', fontsize=11, verticalalignment='top')\n",
        "\n",
        "    #plt.show()\n",
        "    plt.savefig(f\"2_{pattern_description}.png\", dpi=300)\n",
        "    plt.close()\n",
        "\n",
        "    return sol\n",
        "\n",
        "\n",
        "run_simulation()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 66,
          "referenced_widgets": [
            "d5307aef34cb4a05ac75b67bceae74e5",
            "412b0d94034943c083ae8aacf58eab91",
            "57f8f46259854e889ece5cb50f022c13",
            "45d9cf8618d24e9c82d9d7eb7ba12788",
            "719b2e552dbc463baa27692fb84b2058",
            "d85aed09dc59461eb372563df82e057b",
            "f2bbd9d3e40d40268351cbfd16973086",
            "c30cd1c004f540be90d791f951f8f9b0",
            "af3b27f0a97b4bdab2460751eea65e0a",
            "b02c67e500f945e3b11695212fb093e4",
            "aa772dc511544eea8a730b24fa2acbc7"
          ]
        },
        "id": "wCLoYXop468S",
        "outputId": "75e843f2-e76f-4d6a-da44-53ac1899b45f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "  0%|          | 0/15.0 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "d5307aef34cb4a05ac75b67bceae74e5"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "FieldCollection(ScalarField(...), ScalarField(...))"
            ]
          },
          "metadata": {},
          "execution_count": 3
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "def run_simulation2():\n",
        "\n",
        "    alpha = 0.00017\n",
        "    beta = 0.07\n",
        "    F_str = \"1.3*u - u**3 - v/3 - 0.05\"\n",
        "    G_str = \"3*(0.5*u - v)\"\n",
        "\n",
        "    eq = PDE(\n",
        "        {\n",
        "            \"u\": f\"{alpha} * laplace(u) + ({F_str})\",\n",
        "            \"v\": f\"{beta} * laplace(v) + ({G_str})\",\n",
        "        }\n",
        "    )\n",
        "\n",
        "    grid = CartesianGrid([[0, 3], [0, 3]], [200, 200])\n",
        "\n",
        "    u = ScalarField.random_normal(grid, mean=0.5, std=0.1)\n",
        "    v = ScalarField.random_normal(grid, mean=0.25, std=0.1)\n",
        "    state = FieldCollection([u, v])\n",
        "\n",
        "\n",
        "    sol = eq.solve(state, t_range=15, dt=0.0005, tracker=['progress'])\n",
        "\n",
        "    pattern_description = \"Patrón\"\n",
        "\n",
        "    plt.figure(figsize=(8, 7))\n",
        "    plt.imshow(sol.data[0], cmap='binary')\n",
        "    plt.title(f\"Patrón de Turing: {pattern_description}\", fontsize=14, fontweight='bold')\n",
        "    plt.colorbar(label=\"Concentration\")\n",
        "\n",
        "\n",
        "    plt.text(5, 195,\n",
        "             f'$\\\\bf{{\\\\alpha}} = {alpha}$\\n$\\\\bf{{\\\\beta}} = {beta}$',\n",
        "             color='deepskyblue', fontsize=11, verticalalignment='bottom')\n",
        "\n",
        "    plt.text(5, 5,\n",
        "             f'$\\\\bf{{F(u,v)}} = {F_str}$\\n$\\\\bf{{G(u,v)}} = {G_str}$',\n",
        "             color='deepskyblue', fontsize=11, verticalalignment='top')\n",
        "\n",
        "    #plt.show()\n",
        "    plt.savefig(f\"2_{pattern_description}.png\", dpi=300)\n",
        "    plt.close()\n",
        "    return sol\n",
        "\n",
        "run_simulation2()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 66,
          "referenced_widgets": [
            "f2d74260e9ec42a598305d2299a44943",
            "040dcb4028104032b97c38e0e4ff1808",
            "aaf028446b4249e5be7d4cfe28b1d369",
            "d3aeb127033d408da3b3f89f542e6379",
            "4dcf24d08c094343bad2e7f7deb4e996",
            "a5200e2f0f0b4cd9b96ab844d43b54ea",
            "2b37a2977ecb4881b60a2eceb87959e7",
            "eafb64e439fa48fda7ab4631b71300f5",
            "2869642605d644de97ea595ad163888c",
            "78a1ce26e5544bc885e90810010311bc",
            "0c92d74a90b5488aa84619b3bb4488db"
          ]
        },
        "id": "fozYX-YV5SDv",
        "outputId": "3592cc2e-48d1-4cd0-a651-ef71587be30f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "  0%|          | 0/15.0 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "f2d74260e9ec42a598305d2299a44943"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "FieldCollection(ScalarField(...), ScalarField(...))"
            ]
          },
          "metadata": {},
          "execution_count": 4
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "1zsmuq7F5VQx"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}