{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/mcramireza1/Grupo7_Metodos2/blob/main/T4/Punto_1.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cXKYWcAFshWN",
        "outputId": "1d5c459d-3708-46bd-f753-96e1811ffd39"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting py-pde\n",
            "  Using cached py_pde-0.46.0-py3-none-any.whl.metadata (5.6 kB)\n",
            "Requirement already satisfied: matplotlib>=3.1 in /usr/local/lib/python3.12/dist-packages (from py-pde) (3.10.0)\n",
            "Requirement already satisfied: numba>=0.59 in /usr/local/lib/python3.12/dist-packages (from py-pde) (0.60.0)\n",
            "Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.12/dist-packages (from py-pde) (2.0.2)\n",
            "Requirement already satisfied: scipy>=1.10 in /usr/local/lib/python3.12/dist-packages (from py-pde) (1.16.2)\n",
            "Requirement already satisfied: sympy>=1.9 in /usr/local/lib/python3.12/dist-packages (from py-pde) (1.13.3)\n",
            "Requirement already satisfied: tqdm>=4.66 in /usr/local/lib/python3.12/dist-packages (from py-pde) (4.67.1)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (4.60.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (1.4.9)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (25.0)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (3.2.4)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1->py-pde) (2.9.0.post0)\n",
            "Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.59->py-pde) (0.43.0)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.9->py-pde) (1.3.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1->py-pde) (1.17.0)\n",
            "Using cached py_pde-0.46.0-py3-none-any.whl (331 kB)\n",
            "Installing collected packages: py-pde\n",
            "Successfully installed py-pde-0.46.0\n"
          ]
        }
      ],
      "source": [
        "!pip install py-pde"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "#1a\n",
        "# Oscilador Armonico Simulación  (V(x) = -x^2/50) con Crank–Nicolson + Neumann.Genera frames PNG y los convierte en animation.mp4 usando ffmpeg.\n",
        "\n",
        "\n",
        "import os\n",
        "import time\n",
        "import shutil\n",
        "import subprocess\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy import sparse\n",
        "from scipy.sparse.linalg import splu\n",
        "\n",
        "\n",
        "# Parámetros\n",
        "\n",
        "alpha = 0.1                # del enunciado (controla término cinético)\n",
        "x_min, x_max = -20.0, 20.0\n",
        "Nx = 801                   # número de puntos espaciales\n",
        "x = np.linspace(x_min, x_max, Nx)\n",
        "dx = x[1] - x[0]\n",
        "\n",
        "t_final = 150.0            # tiempo final\n",
        "dt = 0.01                  # paso temporal\n",
        "Nt = int(np.round(t_final / dt))\n",
        "\n",
        "# Modo preview para pruebas rápidas\n",
        "preview = False\n",
        "if preview:\n",
        "    print(\"[INFO] MODO PREVIEW activado: pasos reducidos\")\n",
        "    Nt = 200\n",
        "    t_final = Nt * dt\n",
        "\n",
        "print(f\"[INFO] Nx={Nx}, dx={dx:.4f}, dt={dt}, Nt={Nt}, t_final={t_final}\")\n",
        "\n",
        "\n",
        "# Potencial y condición inicial\n",
        "\n",
        "def V_harmonico(x):\n",
        "    return x**2 / 50.0\n",
        "\n",
        "V = V_harmonico(x)\n",
        "\n",
        "# Paquete gaussiano desplazado con fase\n",
        "x0 = 10.0\n",
        "k0 = 2.0\n",
        "def psi0(x):\n",
        "    return np.exp(-2.0 * (x - x0)**2) * np.exp(-1j * k0 * x)\n",
        "\n",
        "psi = psi0(x)\n",
        "\n",
        "# normalizar numéricamente: ∫ |ψ|^2 dx = 1\n",
        "norm = np.sqrt(np.sum(np.abs(psi)**2) * dx)\n",
        "psi /= norm\n",
        "\n",
        "\n",
        "# Laplaciana con condiciones de Neumann\n",
        "\n",
        "diag = np.full(Nx, -2.0) / dx**2\n",
        "off  = np.full(Nx-1, 1.0) / dx**2\n",
        "L = sparse.diags([off, diag, off], offsets=[-1,0,1], format='lil')\n",
        "\n",
        "# ajustar extremos para Neumann\n",
        "L[0,:] = 0.0\n",
        "L[0,0] = -2.0/dx**2\n",
        "L[0,1] = 2.0/dx**2\n",
        "L[-1,:] = 0.0\n",
        "L[-1,-1] = -2.0/dx**2\n",
        "L[-1,-2] = 2.0/dx**2\n",
        "\n",
        "L = L.tocsc()\n",
        "V_diag = sparse.diags(V, 0, format='csc')\n",
        "H = -alpha * L + V_diag\n",
        "\n",
        "\n",
        "# Crank–Nicolson matrices A and B\n",
        "# (I + i dt/2 H) ψ^{n+1} = (I - i dt/2 H) ψ^n\n",
        "\n",
        "I = sparse.identity(Nx, format='csc')\n",
        "A = I + 1j * dt / 2.0 * H\n",
        "B = I - 1j * dt / 2.0 * H\n",
        "\n",
        "# LU factorization de A para resolver cada paso\n",
        "t0 = time.time()\n",
        "A_factor = splu(A)\n",
        "t1 = time.time()\n",
        "print(f\"[INFO] Factorización LU completada en {t1 - t0:.3f} s\")\n",
        "\n",
        "\n",
        "# Observables: <x> y sigma\n",
        "\n",
        "def expectation_x(psi, x):\n",
        "    return np.sum(x * (np.abs(psi)**2)) * dx\n",
        "\n",
        "def expectation_x2(psi, x):\n",
        "    return np.sum((x**2) * (np.abs(psi)**2)) * dx\n",
        "\n",
        "\n",
        "# Bucle temporal, guardado de snapshots\n",
        "\n",
        "times = np.linspace(0, t_final, Nt+1)\n",
        "mu_t = np.zeros(Nt+1, dtype=float)\n",
        "sigma_t = np.zeros(Nt+1, dtype=float)\n",
        "\n",
        "mu_t[0] = expectation_x(psi, x)\n",
        "sigma_t[0] = np.sqrt(max(0.0, expectation_x2(psi, x) - mu_t[0]**2))\n",
        "\n",
        "psi_n = psi.copy()\n",
        "\n",
        "# decidir cuántos snapshots aprox queremos (300 por defecto para buena animación)\n",
        "target_snapshots = 300 if not preview else 60\n",
        "save_every = max(1, Nt // target_snapshots)\n",
        "print(f\"[INFO] Guardando snapshots cada {save_every} pasos ≈ {target_snapshots} snapshots\")\n",
        "\n",
        "snapshots = []\n",
        "snapshot_times = []\n",
        "\n",
        "t_start = time.time()\n",
        "for n in range(1, Nt+1):\n",
        "    # right-hand side\n",
        "    b = B.dot(psi_n)\n",
        "    # resolver A ψ^{n+1} = b\n",
        "    psi_np1 = A_factor.solve(b)\n",
        "    # renormalizar para controlar errores numéricos\n",
        "    psi_np1 /= np.sqrt(np.sum(np.abs(psi_np1)**2) * dx)\n",
        "    psi_n = psi_np1\n",
        "\n",
        "    mu_t[n] = expectation_x(psi_n, x)\n",
        "    sigma_t[n] = np.sqrt(max(0.0, expectation_x2(psi_n, x) - mu_t[n]**2))\n",
        "\n",
        "    if (n % save_every == 0) or (n == Nt):\n",
        "        snapshots.append(psi_n.copy())\n",
        "        snapshot_times.append(n * dt)\n",
        "t_end = time.time()\n",
        "print(f\"[INFO] Evolución completada en {t_end - t_start:.1f} s, snapshots: {len(snapshots)}\")\n",
        "\n",
        "\n",
        "# Preparar frames con matplotlib (fijas escalas para evitar saltos)\n",
        "\n",
        "frames_dir = \"frames\"\n",
        "if os.path.exists(frames_dir):\n",
        "    print(f\"[INFO] Limpiando directorio existente {frames_dir}\")\n",
        "    shutil.rmtree(frames_dir)\n",
        "os.makedirs(frames_dir, exist_ok=True)\n",
        "\n",
        "# Preparar figura y ejes\n",
        "fig, axs = plt.subplots(2, 1, figsize=(10, 8), constrained_layout=True)\n",
        "\n",
        "# Normalizaciones y límites fijos para consistencia visual\n",
        "prob_max = np.max(np.abs(snapshots[0])**2) * 1.2  # límite y escala para densidad\n",
        "if np.max(np.abs(V)) > 0:\n",
        "    V_scaled = V / np.max(np.abs(V)) * prob_max\n",
        "else:\n",
        "    V_scaled = np.zeros_like(V)\n",
        "\n",
        "axs[0].set_xlim(x_min, x_max)\n",
        "axs[0].set_ylim(0.0, prob_max)\n",
        "axs[0].set_xlabel(\"x\")\n",
        "axs[0].set_ylabel(r\"$|\\psi(x,t)|^2$\")\n",
        "axs[0].plot(x, V_scaled, 'k--', linewidth=1.0, label=\"V(x) escalado\")\n",
        "axs[0].legend()\n",
        "axs[0].set_title(\"Evolución de la densidad de probabilidad\")\n",
        "\n",
        "axs[1].set_xlim(0.0, t_final)\n",
        "# definir límites verticales de la banda usando mu_t y sigma_t\n",
        "mu_min = np.min(mu_t) if np.any(mu_t) else -10.0\n",
        "mu_max = np.max(mu_t) if np.any(mu_t) else 10.0\n",
        "sigma_max = np.max(sigma_t) if np.any(sigma_t) else 1.0\n",
        "axs[1].set_ylim(mu_min - 2*sigma_max, mu_max + 2*sigma_max)\n",
        "axs[1].set_xlabel(\"t\")\n",
        "axs[1].set_ylabel(r\"$\\langle x\\rangle$ y $\\sigma$\")\n",
        "axs[1].set_title(\"Posición esperada y banda de incertidumbre\")\n",
        "\n",
        "# pre-dibujar (vacío) la línea de mu para actualizar después\n",
        "line_mu, = axs[1].plot([], [], color='C1', lw=1.5, label=r'$\\mu(t)$')\n",
        "axs[1].legend()\n",
        "\n",
        "\n",
        "# Generar y guardar frames PNG (limpiando correctamente las líneas y colecciones previas)\n",
        "\n",
        "print(\"[INFO] Generando frames PNG...\")\n",
        "for i, (psi_snap, t_snap) in enumerate(zip(snapshots, snapshot_times)):\n",
        "\n",
        "\n",
        "    while len(axs[0].lines) > 1:\n",
        "        axs[0].lines[-1].remove()   #  Limpieza de trazados previos\n",
        "\n",
        "    # eliminar colecciones (fill_between) anteriores en axs[1] correctamente:\n",
        "    prev_collections = list(axs[1].collections)\n",
        "    for coll in prev_collections:\n",
        "        try:\n",
        "            coll.remove()\n",
        "        except Exception:\n",
        "            # en caso de que no se pueda remover, ignoramos y seguimos\n",
        "            pass\n",
        "\n",
        "    # eliminar líneas\n",
        "    prev_lines = list(axs[1].lines)\n",
        "    for ln in prev_lines:\n",
        "\n",
        "        try:\n",
        "            ln.remove()\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    # panel 0: densidad de probabilidad actual\n",
        "    axs[0].plot(x, np.abs(psi_snap)**2, color='C0', lw=1.2)\n",
        "\n",
        "    # panel 1: rellenar la banda mu ± sigma hasta el tiempo actual y trazar mu(t)\n",
        "    t_idx = int(np.searchsorted(times, t_snap))\n",
        "    # evitar índices fuera de rango\n",
        "    t_idx = min(t_idx, len(times) - 1)\n",
        "    axs[1].fill_between(times[:t_idx+1], mu_t[:t_idx+1] - sigma_t[:t_idx+1], mu_t[:t_idx+1] + sigma_t[:t_idx+1], alpha=0.3)\n",
        "    axs[1].plot(times[:t_idx+1], mu_t[:t_idx+1], color='C1', lw=1.5)\n",
        "\n",
        "    # anotación con el tiempo actual\n",
        "    text_time = axs[0].text(0.02, 0.92, f\"t = {t_snap:.2f}\", transform=axs[0].transAxes, fontsize=10,\n",
        "                             bbox=dict(facecolor='white', alpha=0.6, edgecolor='none'))\n",
        "\n",
        "    # guardar frame\n",
        "    frame_filename = os.path.join(frames_dir, f\"frame_{i:04d}.png\")\n",
        "    plt.savefig(frame_filename, dpi=150)\n",
        "    # remover la anotación para no acumularla\n",
        "    text_time.remove()\n",
        "\n",
        "print(f\"[INFO] Frames guardados en {frames_dir} (total {len(snapshots)})\")\n",
        "\n",
        "\n",
        "# ffmpeg para crear animation.mp4\n",
        "\n",
        "fps = 20\n",
        "output_mp4 = \"1.a.mp4\"\n",
        "\n",
        "ffmpeg_cmd = [\n",
        "    \"ffmpeg\",\n",
        "    \"-y\",  # overwrite\n",
        "    \"-framerate\", str(fps),\n",
        "    \"-i\", os.path.join(frames_dir, \"frame_%04d.png\"),\n",
        "    \"-c:v\", \"libx264\",\n",
        "    \"-pix_fmt\", \"yuv420p\",\n",
        "    \"-crf\", \"18\",\n",
        "    output_mp4\n",
        "]\n",
        "\n",
        "print(\"[INFO] Ejecutando ffmpeg para crear el video...\")\n",
        "print(\"Comando:\", \" \".join(ffmpeg_cmd))\n",
        "try:\n",
        "    subprocess.run(ffmpeg_cmd, check=True)\n",
        "    print(f\"[INFO] Video creado: {output_mp4}\")\n",
        "except FileNotFoundError:\n",
        "    print(\"[ERROR] ffmpeg no encontrado: instala ffmpeg (ej. apt install ffmpeg) o añade ffmpeg a PATH.\")\n",
        "except subprocess.CalledProcessError as e:\n",
        "    print(\"[ERROR] ffmpeg falló:\", e)\n",
        "\n",
        "\n",
        "# Limpieza de frames\n",
        "\n",
        "cleanup_frames = True\n",
        "if cleanup_frames:\n",
        "    try:\n",
        "        shutil.rmtree(frames_dir)\n",
        "        print(f\"[INFO] Frames temporales eliminados: {frames_dir}\")\n",
        "    except Exception as e:\n",
        "        print(\"[WARNING] No se pudieron eliminar frames:\", e)\n",
        "\n",
        "print(\"[DONE]\")"
      ],
      "metadata": {
        "id": "ZjZxtmExfdjP",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "f91eed88-65b2-4c4b-a87e-a9ad4c0a3316"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[INFO] Nx=801, dx=0.0500, dt=0.01, Nt=15000, t_final=150.0\n",
            "[INFO] Factorización LU completada en 0.001 s\n",
            "[INFO] Guardando snapshots cada 50 pasos ≈ 300 snapshots\n",
            "[INFO] Evolución completada en 6.2 s, snapshots: 300\n",
            "[INFO] Limpiando directorio existente frames\n",
            "[INFO] Generando frames PNG...\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#1b Oscilador cuartico Simulación del oscilador cuártico V(x)=(x/5)^4 con Crank–Nicolson + Neumann BC.\n",
        "\n",
        "\n",
        "import os\n",
        "import time\n",
        "import shutil\n",
        "import subprocess\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy import sparse\n",
        "from scipy.sparse.linalg import splu\n",
        "\n",
        "\n",
        "# Parámetros\n",
        "\n",
        "alpha = 0.1\n",
        "x_min, x_max = -20.0, 20.0\n",
        "Nx = 801\n",
        "x = np.linspace(x_min, x_max, Nx)\n",
        "dx = x[1] - x[0]\n",
        "\n",
        "t_final = 50.0    # Enunciado pide t = 50\n",
        "dt = 0.01\n",
        "Nt = int(np.round(t_final / dt))\n",
        "\n",
        "# Modo preview para pruebas rápidas\n",
        "preview = False\n",
        "if preview:\n",
        "    print(\"[INFO] PREVIEW mode ON (reduced steps)\")\n",
        "    Nt = 200\n",
        "    t_final = Nt * dt\n",
        "\n",
        "print(f\"[INFO] Nx={Nx}, dx={dx:.4f}, dt={dt}, Nt={Nt}, t_final={t_final}\")\n",
        "\n",
        "\n",
        "# Potencial cuártico y condición inicial\n",
        "\n",
        "def V_cuartico(x):\n",
        "    return (x / 5.0) ** 4\n",
        "\n",
        "V = V_cuartico(x)\n",
        "\n",
        "x0 = 10.0\n",
        "k0 = 2.0\n",
        "def psi0(x):\n",
        "    return np.exp(-2.0 * (x - x0)**2) * np.exp(-1j * k0 * x)\n",
        "\n",
        "psi = psi0(x)\n",
        "\n",
        "psi /= np.sqrt(np.sum(np.abs(psi)**2) * dx)\n",
        "\n",
        "\n",
        "# Laplaciana con Neumann\n",
        "\n",
        "diag = np.full(Nx, -2.0) / dx**2\n",
        "off  = np.full(Nx-1, 1.0) / dx**2\n",
        "L = sparse.diags([off, diag, off], offsets=[-1,0,1], format='lil')\n",
        "\n",
        "# Extremos Neumann\n",
        "L[0,:] = 0.0\n",
        "L[0,0] = -2.0/dx**2\n",
        "L[0,1] = 2.0/dx**2\n",
        "L[-1,:] = 0.0\n",
        "L[-1,-1] = -2.0/dx**2\n",
        "L[-1,-2] = 2.0/dx**2\n",
        "\n",
        "L = L.tocsc()\n",
        "V_diag = sparse.diags(V, 0, format='csc')\n",
        "H = -alpha * L + V_diag\n",
        "\n",
        "\n",
        "# Crank–Nicolson matrices\n",
        "\n",
        "I = sparse.identity(Nx, format='csc')\n",
        "A = I + 1j * dt / 2.0 * H\n",
        "B = I - 1j * dt / 2.0 * H\n",
        "\n",
        "t0 = time.time()\n",
        "A_factor = splu(A)\n",
        "t1 = time.time()\n",
        "print(f\"[INFO] LU factorization done in {t1-t0:.3f} s\")\n",
        "\n",
        "\n",
        "# Observables\n",
        "\n",
        "def expectation_x(psi, x):\n",
        "    return np.sum(x * (np.abs(psi)**2)) * dx\n",
        "\n",
        "def expectation_x2(psi, x):\n",
        "    return np.sum((x**2) * (np.abs(psi)**2)) * dx\n",
        "\n",
        "times = np.linspace(0, t_final, Nt+1)\n",
        "mu_t = np.zeros(Nt+1)\n",
        "sigma_t = np.zeros(Nt+1)\n",
        "mu_t[0] = expectation_x(psi, x)\n",
        "sigma_t[0] = np.sqrt(max(0.0, expectation_x2(psi, x) - mu_t[0]**2))\n",
        "\n",
        "psi_n = psi.copy()\n",
        "save_every = max(1, Nt // 300)  # approx 300 snapshots for smooth animation\n",
        "snapshots = []\n",
        "snapshot_times = []\n",
        "\n",
        "print(\"[INFO] Starting time evolution for quartic oscillator...\")\n",
        "tstart = time.time()\n",
        "for n in range(1, Nt+1):\n",
        "    b = B.dot(psi_n)\n",
        "    psi_np1 = A_factor.solve(b)\n",
        "    psi_np1 /= np.sqrt(np.sum(np.abs(psi_np1)**2) * dx)\n",
        "    psi_n = psi_np1\n",
        "    mu_t[n] = expectation_x(psi_n, x)\n",
        "    sigma_t[n] = np.sqrt(max(0.0, expectation_x2(psi_n, x) - mu_t[n]**2))\n",
        "    if (n % save_every == 0) or (n == Nt):\n",
        "        snapshots.append(psi_n.copy())\n",
        "        snapshot_times.append(n * dt)\n",
        "tend = time.time()\n",
        "print(f\"[INFO] Evolution finished in {tend - tstart:.1f} s, snapshots: {len(snapshots)}\")\n",
        "\n",
        "\n",
        "# Preparar frames y figura\n",
        "\n",
        "frames_dir = \"frames_cuartico\"\n",
        "if os.path.exists(frames_dir):\n",
        "    print(f\"[INFO] Cleaning existing {frames_dir}\")\n",
        "    shutil.rmtree(frames_dir)\n",
        "os.makedirs(frames_dir, exist_ok=True)\n",
        "\n",
        "fig, axs = plt.subplots(2,1, figsize=(10,8), constrained_layout=True)\n",
        "\n",
        "# escalas fijas\n",
        "prob_max = np.max(np.abs(snapshots[0])**2) * 1.2\n",
        "V_scaled = V / np.max(np.abs(V)) * prob_max if np.max(np.abs(V)) > 0 else np.zeros_like(V)\n",
        "\n",
        "axs[0].set_xlim(x_min, x_max)\n",
        "axs[0].set_ylim(0.0, prob_max)\n",
        "axs[0].set_xlabel(\"x\")\n",
        "axs[0].set_ylabel(r\"$|\\psi(x,t)|^2$\")\n",
        "axs[0].plot(x, V_scaled, 'k--', linewidth=1.0, label=\"V(x) escalado\")\n",
        "axs[0].legend()\n",
        "axs[0].set_title(\"Densidad de probabilidad - Oscilador cuártico\")\n",
        "\n",
        "axs[1].set_xlim(0.0, t_final)\n",
        "mu_min = np.min(mu_t) if np.any(mu_t) else -10.0\n",
        "mu_max = np.max(mu_t) if np.any(mu_t) else 10.0\n",
        "sigma_max = np.max(sigma_t) if np.any(sigma_t) else 1.0\n",
        "axs[1].set_ylim(mu_min - 2*sigma_max, mu_max + 2*sigma_max)\n",
        "axs[1].set_xlabel(\"t\")\n",
        "axs[1].set_ylabel(r\"$\\langle x\\rangle$ y $\\sigma$\")\n",
        "axs[1].set_title(\"Posición esperada y banda de incertidumbre\")\n",
        "\n",
        "# placeholder line\n",
        "placeholder_line, = axs[1].plot([], [], color='C1', lw=1.5, label=r'$\\mu(t)$')\n",
        "axs[1].legend()\n",
        "\n",
        "\n",
        "# Guardar frames PNG\n",
        "\n",
        "print(\"[INFO] Generating PNG frames...\")\n",
        "for i, (psi_snap, t_snap) in enumerate(zip(snapshots, snapshot_times)):\n",
        "\n",
        "    while len(axs[0].lines) > 1:\n",
        "        axs[0].lines[-1].remove()\n",
        "\n",
        "\n",
        "    prev_collections = list(axs[1].collections)\n",
        "    for coll in prev_collections:\n",
        "        try:\n",
        "            coll.remove()\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    # remover líneas previas en axs\n",
        "    prev_lines = list(axs[1].lines)\n",
        "    for ln in prev_lines:\n",
        "        try:\n",
        "            ln.remove()\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    # dibujar densidad en axs[0]\n",
        "    axs[0].plot(x, np.abs(psi_snap)**2, color='C0', lw=1.2)\n",
        "\n",
        "    # dibujar banda y mu hasta t_snap en axs[1]\n",
        "    t_idx = int(np.searchsorted(times, t_snap))\n",
        "    t_idx = min(t_idx, len(times)-1)\n",
        "    axs[1].fill_between(times[:t_idx+1], mu_t[:t_idx+1] - sigma_t[:t_idx+1], mu_t[:t_idx+1] + sigma_t[:t_idx+1], alpha=0.3)\n",
        "    axs[1].plot(times[:t_idx+1], mu_t[:t_idx+1], color='C1', lw=1.5)\n",
        "\n",
        "    # anotación temporal\n",
        "    text_time = axs[0].text(0.02, 0.92, f\"t = {t_snap:.2f}\", transform=axs[0].transAxes, fontsize=10,\n",
        "                             bbox=dict(facecolor='white', alpha=0.6, edgecolor='none'))\n",
        "\n",
        "    frame_filename = os.path.join(frames_dir, f\"frame_{i:04d}.png\")\n",
        "    plt.savefig(frame_filename, dpi=150)\n",
        "    text_time.remove()\n",
        "\n",
        "print(f\"[INFO] Saved frames in {frames_dir} ({len(snapshots)} images)\")\n",
        "\n",
        "\n",
        "# ffmpeg -> mp4\n",
        "\n",
        "fps = 20\n",
        "output_mp4 = \"1.b.mp4\"\n",
        "ffmpeg_cmd = [\n",
        "    \"ffmpeg\",\n",
        "    \"-y\",\n",
        "    \"-framerate\", str(fps),\n",
        "    \"-i\", os.path.join(frames_dir, \"frame_%04d.png\"),\n",
        "    \"-c:v\", \"libx264\",\n",
        "    \"-pix_fmt\", \"yuv420p\",\n",
        "    \"-crf\", \"18\",\n",
        "    output_mp4\n",
        "]\n",
        "\n",
        "print(\"[INFO] Running ffmpeg to create video...\")\n",
        "try:\n",
        "    subprocess.run(ffmpeg_cmd, check=True)\n",
        "    print(f\"[INFO] Video created: {output_mp4}\")\n",
        "except FileNotFoundError:\n",
        "    print(\"[ERROR] ffmpeg not found. Install ffmpeg (e.g. apt install ffmpeg) or add to PATH.\")\n",
        "except subprocess.CalledProcessError as e:\n",
        "    print(\"[ERROR] ffmpeg failed:\", e)\n",
        "\n",
        "\n",
        "# Limpiar frames temporales\n",
        "\n",
        "cleanup_frames = True\n",
        "if cleanup_frames:\n",
        "    try:\n",
        "        shutil.rmtree(frames_dir)\n",
        "        print(f\"[INFO] Removed frames directory: {frames_dir}\")\n",
        "    except Exception as e:\n",
        "        print(\"[WARNING] Could not remove frames dir:\", e)\n",
        "\n",
        "print(\"[DONE]\")"
      ],
      "metadata": {
        "id": "wGE8ruNIjdSM"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#1c sombrero Simulación del potencial \"sombrero\" V(x) = (1/50) * (x^4/100 - x^2) Usa Crank–Nicolson + condiciones de frontera Neumann.\n",
        "\n",
        "import os\n",
        "import time\n",
        "import shutil\n",
        "import subprocess\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy import sparse\n",
        "from scipy.sparse.linalg import splu\n",
        "\n",
        "\n",
        "# Parámetros\n",
        "\n",
        "alpha = 0.1\n",
        "x_min, x_max = -20.0, 20.0\n",
        "Nx = 801\n",
        "x = np.linspace(x_min, x_max, Nx)\n",
        "dx = x[1] - x[0]\n",
        "\n",
        "t_final = 150.0\n",
        "dt = 0.01\n",
        "Nt = int(np.round(t_final / dt))\n",
        "\n",
        "# Opcional: modo preview para pruebas rápidas\n",
        "preview = False\n",
        "if preview:\n",
        "    print(\"[INFO] PREVIEW ON: pasos reducidos\")\n",
        "    Nt = 200\n",
        "    t_final = Nt * dt\n",
        "\n",
        "print(f\"[INFO] Nx={Nx}, dx={dx:.4f}, dt={dt}, Nt={Nt}, t_final={t_final}\")\n",
        "\n",
        "\n",
        "# Potencial sombrero e inicial\n",
        "\n",
        "def V_sombrero(x):\n",
        "    return (1.0/50.0) * ((x**4) / 100.0 - x**2)\n",
        "\n",
        "V = V_sombrero(x)\n",
        "\n",
        "x0 = 10.0\n",
        "k0 = 2.0\n",
        "def psi0(x):\n",
        "    return np.exp(-2.0 * (x - x0)**2) * np.exp(-1j * k0 * x)\n",
        "\n",
        "psi = psi0(x)\n",
        "psi /= np.sqrt(np.sum(np.abs(psi)**2) * dx)   # normalizar\n",
        "\n",
        "\n",
        "# Laplaciana Neumann\n",
        "\n",
        "diag = np.full(Nx, -2.0) / dx**2\n",
        "off  = np.full(Nx-1, 1.0) / dx**2\n",
        "L = sparse.diags([off, diag, off], offsets=[-1,0,1], format='lil')\n",
        "\n",
        "# ajustar extremos para Neumann\n",
        "L[0,:] = 0.0\n",
        "L[0,0] = -2.0/dx**2\n",
        "L[0,1] = 2.0/dx**2\n",
        "L[-1,:] = 0.0\n",
        "L[-1,-1] = -2.0/dx**2\n",
        "L[-1,-2] = 2.0/dx**2\n",
        "\n",
        "L = L.tocsc()\n",
        "V_diag = sparse.diags(V, 0, format='csc')\n",
        "H = -alpha * L + V_diag\n",
        "\n",
        "\n",
        "# Crank–Nicolson matrices\n",
        "\n",
        "I = sparse.identity(Nx, format='csc')\n",
        "A = I + 1j * dt / 2.0 * H\n",
        "B = I - 1j * dt / 2.0 * H\n",
        "\n",
        "t0 = time.time()\n",
        "A_factor = splu(A)\n",
        "t1 = time.time()\n",
        "print(f\"[INFO] LU factorization done in {t1 - t0:.3f} s\")\n",
        "\n",
        "\n",
        "# Observables\n",
        "\n",
        "def expectation_x(psi, x):\n",
        "    return np.sum(x * (np.abs(psi)**2)) * dx\n",
        "\n",
        "def expectation_x2(psi, x):\n",
        "    return np.sum((x**2) * (np.abs(psi)**2)) * dx\n",
        "\n",
        "times = np.linspace(0, t_final, Nt+1)\n",
        "mu_t = np.zeros(Nt+1)\n",
        "sigma_t = np.zeros(Nt+1)\n",
        "mu_t[0] = expectation_x(psi, x)\n",
        "sigma_t[0] = np.sqrt(max(0.0, expectation_x2(psi, x) - mu_t[0]**2))\n",
        "\n",
        "psi_n = psi.copy()\n",
        "# número de snapshots objetivo para animación\n",
        "target_snapshots = 300 if not preview else 60\n",
        "save_every = max(1, Nt // target_snapshots)\n",
        "snapshots = []\n",
        "snapshot_times = []\n",
        "\n",
        "\n",
        "# Evolución temporal y almacenamiento de snapshots\n",
        "\n",
        "print(\"[INFO] Starting time evolution for sombrero potential...\")\n",
        "t_start = time.time()\n",
        "for n in range(1, Nt+1):\n",
        "    b = B.dot(psi_n)\n",
        "    psi_np1 = A_factor.solve(b)\n",
        "    psi_np1 /= np.sqrt(np.sum(np.abs(psi_np1)**2) * dx)  # renormalizar\n",
        "    psi_n = psi_np1\n",
        "\n",
        "    mu_t[n] = expectation_x(psi_n, x)\n",
        "    sigma_t[n] = np.sqrt(max(0.0, expectation_x2(psi_n, x) - mu_t[n]**2))\n",
        "\n",
        "    if (n % save_every == 0) or (n == Nt):\n",
        "        snapshots.append(psi_n.copy())\n",
        "        snapshot_times.append(n * dt)\n",
        "t_end = time.time()\n",
        "print(f\"[INFO] Evolution finished in {t_end - t_start:.1f} s, snapshots: {len(snapshots)}\")\n",
        "\n",
        "\n",
        "# Preparar frames (matplotlib) con límites fijos\n",
        "\n",
        "frames_dir = \"frames_sombrero\"\n",
        "if os.path.exists(frames_dir):\n",
        "    print(f\"[INFO] Removing existing frames dir {frames_dir}\")\n",
        "    shutil.rmtree(frames_dir)\n",
        "os.makedirs(frames_dir, exist_ok=True)\n",
        "\n",
        "fig, axs = plt.subplots(2, 1, figsize=(10, 8), constrained_layout=True)\n",
        "\n",
        "# Escalas fijas para evitar saltos en la animación\n",
        "prob_max = np.max(np.abs(snapshots[0])**2) * 1.2\n",
        "V_scaled = V / np.max(np.abs(V)) * prob_max if np.max(np.abs(V)) > 0 else np.zeros_like(V)\n",
        "\n",
        "axs[0].set_xlim(x_min, x_max)\n",
        "axs[0].set_ylim(0.0, prob_max)\n",
        "axs[0].set_xlabel(\"x\")\n",
        "axs[0].set_ylabel(r\"$|\\psi(x,t)|^2$\")\n",
        "axs[0].plot(x, V_scaled, 'k--', linewidth=1.0, label=\"V(x) escalado\")\n",
        "axs[0].legend()\n",
        "axs[0].set_title(\"Densidad de probabilidad - Potencial Sombrero\")\n",
        "\n",
        "axs[1].set_xlim(0.0, t_final)\n",
        "mu_min = np.min(mu_t) if np.any(mu_t) else -10.0\n",
        "mu_max = np.max(mu_t) if np.any(mu_t) else 10.0\n",
        "sigma_max = np.max(sigma_t) if np.any(sigma_t) else 1.0\n",
        "axs[1].set_ylim(mu_min - 2*sigma_max, mu_max + 2*sigma_max)\n",
        "axs[1].set_xlabel(\"t\")\n",
        "axs[1].set_ylabel(r\"$\\langle x\\rangle$ y $\\sigma$\")\n",
        "axs[1].set_title(\"Posición esperada y banda de incertidumbre\")\n",
        "\n",
        "\n",
        "placeholder_line, = axs[1].plot([], [], color='C1', lw=1.5, label=r'$\\mu(t)$')\n",
        "axs[1].legend()\n",
        "\n",
        "\n",
        "# Generar y guardar frames PNG\n",
        "\n",
        "print(\"[INFO] Generating PNG frames...\")\n",
        "for i, (psi_snap, t_snap) in enumerate(zip(snapshots, snapshot_times)):\n",
        "\n",
        "    while len(axs[0].lines) > 1:\n",
        "        axs[0].lines[-1].remove()\n",
        "\n",
        "\n",
        "    prev_collections = list(axs[1].collections)\n",
        "    for coll in prev_collections:\n",
        "        try:\n",
        "            coll.remove()\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    # remover líneas previas en axs[1]\n",
        "    prev_lines = list(axs[1].lines)\n",
        "    for ln in prev_lines:\n",
        "        try:\n",
        "            ln.remove()\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "\n",
        "    axs[0].plot(x, np.abs(psi_snap)**2, color='C0', lw=1.2)\n",
        "\n",
        "    # panel 1: banda y mu hasta t_snap\n",
        "    t_idx = int(np.searchsorted(times, t_snap))\n",
        "    t_idx = min(t_idx, len(times)-1)\n",
        "    axs[1].fill_between(times[:t_idx+1], mu_t[:t_idx+1] - sigma_t[:t_idx+1], mu_t[:t_idx+1] + sigma_t[:t_idx+1], alpha=0.3)\n",
        "    axs[1].plot(times[:t_idx+1], mu_t[:t_idx+1], color='C1', lw=1.5)\n",
        "\n",
        "    # anotación temporal\n",
        "    text_time = axs[0].text(0.02, 0.92, f\"t = {t_snap:.2f}\", transform=axs[0].transAxes, fontsize=10,\n",
        "                             bbox=dict(facecolor='white', alpha=0.6, edgecolor='none'))\n",
        "\n",
        "    # guardar frame\n",
        "    frame_filename = os.path.join(frames_dir, f\"frame_{i:04d}.png\")\n",
        "    plt.savefig(frame_filename, dpi=150)\n",
        "    # quitar anotación para siguiente frame\n",
        "    text_time.remove()\n",
        "\n",
        "print(f\"[INFO] Frames saved in {frames_dir} ({len(snapshots)} images)\")\n",
        "\n",
        "\n",
        "# ffmpeg para .mp4\n",
        "\n",
        "fps = 20\n",
        "output_mp4 = \"1.c.mp4\"\n",
        "ffmpeg_cmd = [\n",
        "    \"ffmpeg\",\n",
        "    \"-y\",  # overwrite\n",
        "    \"-framerate\", str(fps),\n",
        "    \"-i\", os.path.join(frames_dir, \"frame_%04d.png\"),\n",
        "    \"-c:v\", \"libx264\",\n",
        "    \"-pix_fmt\", \"yuv420p\",\n",
        "    \"-crf\", \"18\",\n",
        "    output_mp4\n",
        "]\n",
        "\n",
        "print(\"[INFO] Running ffmpeg to create video...\")\n",
        "try:\n",
        "    subprocess.run(ffmpeg_cmd, check=True)\n",
        "    print(f\"[INFO] Video created: {output_mp4}\")\n",
        "except FileNotFoundError:\n",
        "    print(\"[ERROR] ffmpeg not found. Install ffmpeg (e.g. apt install ffmpeg) or add to PATH.\")\n",
        "except subprocess.CalledProcessError as e:\n",
        "    print(\"[ERROR] ffmpeg failed:\", e)\n",
        "\n",
        "\n",
        "# Limpieza de frames temporales (opcional)\n",
        "\n",
        "cleanup_frames = True\n",
        "if cleanup_frames:\n",
        "    try:\n",
        "        shutil.rmtree(frames_dir)\n",
        "        print(f\"[INFO] Removed frames directory: {frames_dir}\")\n",
        "    except Exception as e:\n",
        "        print(\"[WARNING] Could not remove frames dir:\", e)\n",
        "\n",
        "print(\"[DONE]\")"
      ],
      "metadata": {
        "id": "KYUE3WbGjiom"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "fwIy11HcukyH"
      },
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}