# -*- coding: utf-8 -*-
"""Tarea_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GeNTLfl_w2cF3iay7Qxq6AFpcTUWBb9
"""

#punto 1
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from PIL import Image

def generate_data(tmax,dt,A,freq,noise):
  ts = np.arange(0,tmax+dt,dt)
  ys = np.random.normal(loc=A*np.sin(2*np.pi*ts*freq),scale=noise)
  return ts, ys

ts, ys = generate_data(tmax=1, dt= 0.01, A = 1.0, freq = 5.0, noise=0.2)
fs = 1/0.01 #frecuencia de muestreo
f_N = fs/2 #frecuencia de Nyquist
f_max = 2.7*f_N
freqs = np.arange(0,f_max, 0.1)
def Fourier_transform(ts,ys,freqs):
  F =[]
  for f in freqs:
    trans = np.sum(ys*np.exp(-1j*2*np.pi*f*ts))
    F.append(trans)
  return np.array(F)

espectro = Fourier_transform(ts,ys,freqs)
plt.figure()
plt.plot(freqs, np.abs(espectro))
plt.xlabel("Frecuencia [Hz]")
plt.ylabel("|F(f)|")
plt.title("Transformada de Fourier")
plt.savefig("1.a.pdf")
plt.close()

def amplitud(SNtime,freq):
  return SNtime * freq

SNtime = 0.1
freq = 5.0
A = amplitud(SNtime,freq)

datos = generate_data(tmax=1, dt= 0.01, A = A, freq = 5.0, noise=0.2)
ts, ys = datos

freqs = np.arange(0,2.7*(1/(2*0.01)), 1)
F = Fourier_transform(ts,ys,freqs)

def snr_freq1(freqs, F, freq0=5.0, df_peak=2, W_excl=10, fmin_bg=1):
  freqs = np.asarray(freqs)
  S = np.abs(F)

  peak_mask = (freqs >= freq0 - df_peak) & (freqs <= freq0 + df_peak)
  if not np.any(peak_mask):  # guardia
      return np.nan
  S_pico = S[peak_mask].max()

  bg_mask = (freqs >= fmin_bg) & ((freqs < freq0 - W_excl) | (freqs > freq0 + W_excl))
  if np.sum(bg_mask) < 5:     # guardia mínima de puntos
      # fallback: usar todo lo que no está en la ventana de búsqueda del pico
      bg_mask = ~peak_mask

  sigma_fondo = np.std(S[bg_mask])
  if sigma_fondo == 0:
      return np.nan

  SNR = S_pico / sigma_fondo
  return SNR

SNtimes = np.logspace(0.01,1,30)
SNTvalues = []
for SNt in SNtimes:
  freq = 5
  A = amplitud(SNt,freq)
  data = generate_data(tmax=1, dt= 0.01, A = A, freq = 5, noise=0.2)
  ts, ys = data
  F = Fourier_transform(ts,ys,freqs)
  SNR = SNTvalues.append(snr_freq1(freqs, F, freq))

plt.figure()
plt.loglog(SNtimes, SNTvalues, 'o-')
plt.xlabel("SN_time")
plt.ylabel("SN_freq")
plt.title("Relación SN en tiempo vs SN en frecuencia")
plt.savefig("1.b_SN.pdf")
plt.close()

def FWHM(freqs, y_ajustada):
    mitad = np.max(y_ajustada) / 2
    indices = np.where(y_ajustada >= mitad)[0]
    if len(indices) < 2:
        return np.nan
    return freqs[indices[-1]] - freqs[indices[0]]

tmax = np.arange(1, 10, 2)
dt = 0.01
A = 1.0
freq = 5.0
noise = 0.2
fs = 1/dt
f_N = fs/2
f_max = 2.7*f_N
freqs = np.arange(0,f_max, 0.1)

plt.figure(figsize=(12, 8))

fwhm_values = []
for i, t in enumerate(tmax, 1):
    ts, ys = generate_data(t, dt, A, freq, noise)
    F = Fourier_transform(ts, ys, freqs)

    w = FWHM(freqs, np.abs(F))
    if np.isnan(w):
        w = 0
    fwhm_values.append(w)

    plt.subplot(2, 3, i)
    plt.plot(freqs, np.abs(F))
    plt.xlim(0, 15)
    plt.title(f"tmax = {t:.2f} s")
    plt.xlabel("Frecuencia [Hz]")
    plt.ylabel("|F(f)|")

plt.tight_layout()
plt.savefig("1.b_freq.pdf")
plt.close()

plt.figure(figsize=(7,5))
plt.plot(tmax, fwhm_values, "o-", lw=2)
plt.xlabel("tmax [s]")
plt.ylabel("Ancho del pico [Hz]")
plt.title("tmax Vs el ancho del pico")
plt.grid(True)
plt.savefig("1.c.pdf")
plt.close()

#punto 2
import pandas as pd

df = pd.read_csv("SN_d_tot_V2.0.csv")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive
from scipy import signal

#drive.mount('/content/drive')
#file_path = '/content/drive/MyDrive/SN_d_tot_V2.0.csv'
#df = pd.read_csv(file_path)

df["spots"] = df["spots"].replace(-1, np.nan)

df["spots_interp"] = df["spots"].interpolate(method="linear", limit_direction='both')

decimal = df['decimal_date'].values
t_days = (decimal - decimal[0]) * 365.25

dt_array = np.diff(t_days)
dt_med = np.median(dt_array)

data = df['spots_interp'].values
valid = ~np.isnan(data)
t_days_v = t_days[valid]
data_v = data[valid]

N = len(data_v)
dt = dt_med

data_detr = signal.detrend(data_v) # quita tendencia lineal
window = np.hanning(N)
data_win = data_detr * window

fft_vals = np.fft.rfft(data_win)
freqs = np.fft.rfftfreq(N, d=dt) # ciclos/día
power = np.abs(fft_vals)**2

# Selección de rango
min_period = 2000.0
max_period = 6000.0
mask = (freqs > 0) & (1.0/freqs >= min_period) & (1.0/freqs <= max_period)

if np.any(mask):
    idx_range = np.argmax(power[mask])
    freqs_in = freqs[mask]
    f_dom = freqs_in[idx_range]
    period_dom = 1.0 / f_dom  # ciclo solar en días

    # Guardar
    with open("2.b.txt", "w") as f:
        f.write(f"{period_dom:.6f}")

from matplotlib.backends.backend_pdf import PdfPages

cutoff_period = 1400.0   # días
cutoff_freq = 1.0 / cutoff_period  # ciclos/día

# FFT
fft_vals = np.fft.rfft(data_v)
freqs = np.fft.rfftfreq(N, d=dt)

mask = freqs <= cutoff_freq

filtrado = fft_vals * mask

# Señal filtrada (transformada inversa)
data_filt_fft = np.fft.irfft(filtrado, n=N)
data_filt_fft[data_filt_fft < 0] = 0

with PdfPages("2.b.data.pdf") as pdf:
    plt.figure(figsize=(12,6))
    plt.plot(t_days_v/365.25, data_v, color="gray", alpha=0.6, label="Original (interpolado)")
    plt.plot(t_days_v/365.25, data_filt_fft, color="blue", linewidth=2, label="Filtrado (FFT pasa bajas)")
    plt.xlabel("Año")
    plt.ylabel("Número de manchas")
    plt.title("Filtro pasa bajas en dominio FFT")
    plt.legend()
    plt.grid(True)
    pdf.savefig()
    plt.close()

# Convertir días a años reales
year0 = 1818  # reemplaza por el año real de inicio de tus datos
t_years = year0 + t_days_v / 365.25

# Crear array con los años enteros que cubren la serie
years = np.arange(int(t_years.min()), int(t_years.max()) + 1)

# Listas para guardar máximos por año
year_list = []
max_list = []

# Recorrer cada año y calcular el máximo
for y in years:
    # índices de ese año
    idx = (t_years >= y) & (t_years < y+1)
    if np.any(idx):  # si hay datos en ese año
        year_list.append(y)
        max_list.append(np.max(data_filt_fft[idx]))

# Convertir a arrays
year_list = np.array(year_list)
max_list = np.array(max_list)

# --- Graficar ---
with PdfPages("2.b.maxima.pdf") as pdf:
    plt.figure(figsize=(10,6))
    plt.plot(year_list, max_list, "o-", color="blue", label="Máximos anuales")
    plt.xlabel("Año")
    plt.ylabel("Número de manchas (máximo anual)")
    plt.title("Máximos por año de la señal filtrada")
    plt.grid(True)
    plt.legend()
    pdf.savefig()
    plt.close()

from scipy.signal import find_peaks

# --- Encontrar máximos locales ---
peaks, _ = signal.find_peaks(data_filt_fft, distance=200)
# distance ~200 evita detectar máximos demasiado cercanos (ajusta según tus datos)

# Extraer fechas y valores de los máximos
t_max = t_days_v[peaks] / 365.25   # años
y_max = data_filt_fft[peaks]           # número de manchas en el máximo

# --- Graficar ---
with PdfPages("2.b.maxima_c.pdf") as pdf:
    plt.figure(figsize=(10,6))
    plt.plot(t_max, y_max, "o-", color="blue", label="Máximos locales")
    plt.xlabel("Año del máximo")
    plt.ylabel("Número de manchas en el máximo")
    plt.title("Máximos locales de la señal filtrada")
    plt.grid(True)
    plt.legend()
    pdf.savefig()
    plt.close()

"""# **3.Filtrando imágenes (FFT 2D)**"""

# PUNTO 3.a
imagen = np.array(Image.open("miette.jpg")) #se abre la imagen

sigma = 15 #me permite decidir que tan desenfocada queda la imagen
filas, columnas, _ = imagen.shape #se ignora el valor de la profundidad (canales rgb)

#filtro (pasa bajas), las frecuencias altas son las que tienen detalles. Si se atenúan estas, permite obtener la imagen distorsionada
x = np.linspace(-columnas//2, columnas//2, columnas) #x e y empiezan en 0, se hace //2 para que queden centrados en 0.
y = np.linspace(-filas//2, filas//2, filas) #la gaussiana va a estar centrada en 0
X, Y = np.meshgrid(x, y)
gaussiana = np.exp(-(X**2 + Y**2) / (2*sigma**2)) #def gaussiana

#como la imagen es RGB se debe hacer para los 3 canales
nueva = np.zeros_like(imagen)
for c in range(3):
    F = np.fft.fftshift(np.fft.fft2(imagen[:, :, c])) # solo me interesa trabajar sobre el canal, no los valores x, y
    F_filtrada = F * gaussiana #la multiplicación atenúa las frecuencias altas
    nueva[:, :, c] = np.abs(np.fft.ifft2(np.fft.ifftshift(F_filtrada)))#FFT inversa, guarda la nueva intensidad en el canal que corresponde

#guarda la imagen
plt.imshow(nueva)
plt.axis("off")
plt.savefig("3.a.jpg")
plt.close()

#PUNTO 3.b.a

pato = np.array(Image.open("p_a_t_o.jpg"))
plt.rcParams["image.cmap"] = "magma"
p_p = plt.imshow(pato)
plt.colorbar(p_p)
F_p = np.fft.fft2(pato) #transformada rápida
F_p = np.fft.fftshift(F_p) # shift

Fp_filtered = F_p.copy() #Copia para modificar los valores

# Eliminación picos de manera manual
Fp_filtered[252:259,:250] = 0. #Líneas horizontales
Fp_filtered[252:259,263:]=0.

#Recta con pendiente 1
Fp_filtered[260:263,260:263]=0.
Fp_filtered[263:266,263:266]=0.
Fp_filtered[266:269,266:269]=0.
Fp_filtered[269:272,269:272]=0.
Fp_filtered[272:275,272:275]=0.
Fp_filtered[275:278,275:278]=0.
Fp_filtered[278:281,278:281]=0.
Fp_filtered[281:284,281:284]=0.
Fp_filtered[284:287,284:287]=0.
Fp_filtered[287:290,287:290]=0.
Fp_filtered[290:293,290:293]=0.
Fp_filtered[293:296,293:296]=0.
Fp_filtered[296:299,296:299]=0.
Fp_filtered[299:302,299:302]=0.
Fp_filtered[302:305,302:305]=0.
Fp_filtered[305:308,305:308]=0.
Fp_filtered[308:311,308:311]=0.
Fp_filtered[311:314,311:314]=0.
Fp_filtered[314:317,314:317]=0.
Fp_filtered[317:320,317:320]=0.

Fp_filtered[250:253,250:253]=0.
Fp_filtered[247:250,247:250]=0.
Fp_filtered[244:247,244:247]=0.
Fp_filtered[241:244,241:244]=0.
Fp_filtered[238:241,238:241]=0.
Fp_filtered[235:238,235:238]=0.
Fp_filtered[232:235,232:235]=0.
Fp_filtered[229:232,229:232]=0.
Fp_filtered[226:229,226:229]=0.
Fp_filtered[223:226,223:226]=0.
Fp_filtered[220:223,220:223]=0.
Fp_filtered[217:220,217:220]=0.
Fp_filtered[214:217,214:217]=0.
Fp_filtered[211:214,211:214]=0.
Fp_filtered[208:211,208:211]=0.
Fp_filtered[205:208,205:208]=0.
Fp_filtered[202:205,202:205]=0.
Fp_filtered[199:202,199:202]=0.
Fp_filtered[196:199,196:199]=0.
Fp_filtered[193:196,193:196]=0.
Fp_filtered[190:193,190:193]=0.
Fp_filtered[187:190,187:190]=0.
Fp_filtered[184:187,184:187]=0.
Fp_filtered[181:184,181:184]=0.
Fp_filtered[178:181,178:181]=0.
Fp_filtered[175:178,175:178]=0.
Fp_filtered[172:175,172:175]=0.
Fp_filtered[169:172,169:172]=0.


#Recta con pendiente -0.88
Fp_filtered[260:262,260:262]=0.
Fp_filtered[262:264,261:263]=0.
Fp_filtered[264:266,263:265]=0.
Fp_filtered[266:268,265:267]=0.
Fp_filtered[268:270,267:269]=0.
Fp_filtered[270:272,269:271]=0.
Fp_filtered[272:274,271:273]=0.
Fp_filtered[274:276,273:275]=0.
Fp_filtered[276:278,275:277]=0.
Fp_filtered[278:280,277:279]=0.
Fp_filtered[280:282,279:281]=0.
Fp_filtered[282:284,281:283]=0.
Fp_filtered[284:286,283:285]=0.
Fp_filtered[286:288,285:287]=0.
Fp_filtered[288:290,287:289]=0.
Fp_filtered[290:292,289:291]=0.
Fp_filtered[292:294,291:293]=0.
Fp_filtered[294:296,293:295]=0.
Fp_filtered[296:298,295:297]=0.
Fp_filtered[298:300,297:299]=0.
Fp_filtered[300:302,299:301]=0.
Fp_filtered[302:304,301:303]=0.
Fp_filtered[304:306,303:305]=0.
Fp_filtered[306:308,305:307]=0.
Fp_filtered[308:310,307:309]=0.
Fp_filtered[310:312,309:311]=0.
Fp_filtered[312:314,311:313]=0.
Fp_filtered[314:316,313:315]=0.
Fp_filtered[316:318,315:317]=0.
Fp_filtered[318:320,317:319]=0.

Fp_filtered[250:253,249:252]=0.
Fp_filtered[247:250,246:249]=0.
Fp_filtered[244:247,243:246]=0.
Fp_filtered[241:244,240:243]=0.
Fp_filtered[238:241,237:240]=0.
Fp_filtered[235:238,234:237]=0.
Fp_filtered[232:235,231:234]=0.
Fp_filtered[229:232,228:231]=0.
Fp_filtered[226:229,225:228]=0.
Fp_filtered[223:226,222:225]=0.
Fp_filtered[220:223,221:224]=0.
Fp_filtered[217:220,218:221]=0.
Fp_filtered[214:217,216:219]=0.
Fp_filtered[211:214,215:218]=0.
Fp_filtered[208:211,207:210]=0.
Fp_filtered[205:208,204:207]=0.
Fp_filtered[202:205,202:205]=0.
Fp_filtered[199:202,198:201]=0.
Fp_filtered[196:199,195:198]=0.


#Figura de la transformada con los pedazos modificados
"""plt.figure(figsize=(8,8))
plt.imshow(abs(Fp_filtered),norm="log")
plt.savefig("3.b.a_esp.png")
plt.close()"""
#Inversa FFT, shift y gráfica
pato_filtrada = np.fft.ifft2(np.fft.ifftshift(Fp_filtered))
plt.imshow(pato_filtrada.real)
plt.axis("off")
plt.savefig("3.b.a.jpg")
plt.close()

#PUNTO 3.b.b
gato = np.array(Image.open("g_a_t_o.png"))
plt.rcParams["image.cmap"] = "magma"
p_g = plt.imshow(gato)
plt.colorbar(p_g)
F_g = np.fft.fft2(gato) #se hace la transformada rapida
F_g = np.fft.fftshift(F_g) #shift para que quede centrada

Fg_filtered = F_g.copy() # se hace la copia y se modifican únicamente los pedazos deseados.
#Se ponen en 0 los picos de manera manual
Fg_filtered[173:175,256:304]=0.
Fg_filtered[185:187,264:304]=0.
Fg_filtered[197:199,270:305]=0.
Fg_filtered[209:211,278:315]=0.
Fg_filtered[221:223,287:323]=0.
Fg_filtered[233:236,292:344]=0.
Fg_filtered[245:248,299:355]=0.
Fg_filtered[258:260,305:360]=0.
Fg_filtered[270:272,312:358]=0.
Fg_filtered[281:285,318:357]=0.
Fg_filtered[293:297,326:367]=0.
Fg_filtered[305:309,332:370]=0.
Fg_filtered[317:321,338:377]=0.
Fg_filtered[329:333,344:385]=0.
Fg_filtered[341:345,351:390]=0.
Fg_filtered[353:357,357:385]=0.
Fg_filtered[367:369,:] = 0.
Fg_filtered[390:392,:] = 0.
Fg_filtered[403:406,370:390]=0.
Fg_filtered[414:418,365:400]=0.
Fg_filtered[426:430,370:407]=0.
Fg_filtered[438:442,370:415]=0.
Fg_filtered[450:454,381:420]=0.
Fg_filtered[462:466,382:425]=0.
Fg_filtered[475:478,387:435]=0.
Fg_filtered[488:491,386:438]=0.
Fg_filtered[500:503,383:448]=0.
Fg_filtered[511:514,395:451]=0.
Fg_filtered[523:525,408:458]=0.
Fg_filtered[535:537,421:465]=0.
Fg_filtered[548:551,425:471]=0.
Fg_filtered[560:562,445:483]=0.
Fg_filtered[572:574,425:487]=0.
Fg_filtered[584:574,445:483]=0.

#Figura de la transformada con los pedazos modificados
"""plt.figure(figsize=(8,8))
plt.imshow(abs(Fg_filtered),norm="log")
plt.savefig("3.b.b_esp.png")
plt.close()"""

#Se hace la inversa FFT, shift para volver a la original y se grafica.
gato_filtrada = np.fft.ifft2(np.fft.ifftshift(Fg_filtered))
plt.imshow(gato_filtrada.real)
plt.axis("off")
plt.savefig("3.b.b.png")
plt.close()

#Punto 4
import numpy as np
import matplotlib.pyplot as plt
from astropy.timeseries import LombScargle


# Se leen los datos del archivo: tiempo (días), brillo, error
data = np.loadtxt("/content/OGLE-LMC-CEP-0001.dat")
t = data[:,0]
y = data[:,1]
dy = data[:,2]


# Periodograma de Lomb-Scargle
frequencies = np.linspace(0.01, 2, 10000)  # en ciclos por día
power = LombScargle(t, y, dy).power(frequencies)

# Frecuencia dominante: la de mayor potencia
best_frequency = frequencies[np.argmax(power)]
period = 1 / best_frequency
print(f"Frecuencia dominante: {best_frequency:.5f} ciclos/día")
print(f"Período de la estrella: {period:.5f} días")


# Cálculo fase
phi = np.mod(best_frequency * t, 1)

# Graficar

fig, axs = plt.subplots(2, 1, figsize=(8,10))

# Periodograma
axs[0].plot(frequencies, power, color='darkslateblue')
axs[0].set_xlabel("Frecuencia [ciclos/día]")
axs[0].set_ylabel("Potencia")
axs[0].set_title("Periodograma de Lomb-Scargle")

# Curva de luz plegada
axs[1].errorbar(phi, y, yerr=dy, fmt='o', markersize=2, color='purple', alpha=0.7)
axs[1].invert_yaxis()  # En astronomía, magnitud menor = más brillo
axs[1].set_xlabel("Fase φ")
axs[1].set_ylabel("Brillo (magnitudes)")
axs[1].set_title("Curva de luz de la estrella (plegada)")

plt.tight_layout()
plt.savefig("4.pdf")
plt.close()

#punto 5
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi

img = np.load("7.npy")

#Angulos
#Cada fila es una proyección en cierto ángulo
filas, columnas = img.shape
ang = np.linspace(0., 180., filas, endpoint=False)

freqs = np.fft.fftfreq(columnas).reshape(-1, 1)
freqs_filtrada = np.abs(freqs) #elimina las frecuencias bajas

recon = np.zeros((columnas, columnas)) #Crea la matriz reconstruida de ceros
x = np.arange(-columnas//2, columnas//2)
X, Y = np.meshgrid(x, x)
coords = np.stack((X.ravel(), Y.ravel()))

for i, theta in enumerate(ang):
    proy = img[i, :] #Toma la proyección correspondiente al ángulo
    proy_fft = np.fft.fft(proy) #transformada
    proy_fft_filtrada = proy_fft * freqs_filtrada.ravel() #filtro pasa altas

    proy_filtrada = np.real(np.fft.ifft(proy_fft_filtrada))

    #Retroproyección
    #Forma la imagen ya rotada
    img_rotada = ndi.rotate(
        np.tile(proy_filtrada[:, None], columnas).T,
        -theta,
        reshape=False,
        mode="reflect"
    )
    recon += img_rotada #suma la intensidad para ese ángulo

plt.imsave("4.png", recon, cmap="gray")