# -*- coding: utf-8 -*-
"""T3_ODE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116qynTnJoL3NaHP4gZDJwd0xoC_DmOjH
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.integrate import solve_ivp
from scipy.signal import find_peaks

"""**Punto 1** Cantidades Conservadas"""

#1a Sistema Depredador Presa
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Parámetros y condiciones iniciales indicadas en el enunciado para el sistema
alpha = 2.0
beta = 1.5
gamma = 0.3
delta = 0.4

x0 = 3.0   # decazorros
y0 = 2.0   # kiloconejos
y_init = [x0, y0]

# EcuacionesLotka-Volterra
def lotka_volterra(t, y):
    x, y_p = y
    dxdt = alpha * x - beta * x * y_p
    dydt = -gamma * y_p + delta * x * y_p
    return [dxdt, dydt]

# Intervalo de integración
t_span = (0, 50)
t_eval = np.linspace(0, 50, 1000)

# Resolver el sistema
sol = solve_ivp(lotka_volterra, t_span, y_init, t_eval=t_eval, method="DOP853")

# Graficar resultados
plt.figure(figsize=(8,5))
plt.plot(sol.t, sol.y[0], label="Presas (x) - decazorros", lw=2)
plt.plot(sol.t, sol.y[1], label="Depredadores (y) - kiloconejos", lw=2)
plt.xlabel("Tiempo t")
plt.ylabel("Población")
plt.title("Sistema Depredador-Presa (Lotka-Volterra)")
plt.legend()
plt.grid(True)

plt.savefig("1.a.pdf")

#1.b Landau
# Parámetros y condiciones iniciales indicadas en el enunciado para el sistema
c = 1.0
q = 7.5284
B0 = 0.438
E0 = 0.7423
m = 3.8428
k = 1.0014

# Sistema de ecuaciones
def landau(t, u):
    x, vx, y, vy = u
    dxdt = vx
    dydt = vy
    dvxdt = (q/m) * (E0 * (np.sin(k*x) + k*x*np.cos(k*x)) - B0 * vy)
    dvydt = (q*B0/m) * vx
    return [dxdt, dvxdt, dydt, dvydt]

# Condiciones iniciales
u0 = [0.1, 0.0, 0.0, 0.1]  # x, vx, y, vy

# Intervalo de integración
t_span = (0, 30)
t_eval = np.linspace(0, 30, 2000)

# Resolver EDO
sol = solve_ivp(landau, t_span, u0, t_eval=t_eval, method="DOP853")

x, vx, y, vy = sol.y

# Ecuaciones de Conservación: Momento conjugado y Energía
Pi_y = m*vy - q*B0*x/c
E_tot = 0.5*m*(vx**2 + vy**2) - q*E0*x*np.sin(k*x)

# Ploteo
plt.figure(figsize=(12,8))

# Trayectoria (x,y)
plt.subplot(2,2,1)
plt.plot(x, y, lw=1.5)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Trayectoria en el plano (x,y)")
plt.grid(True)

plt.tight_layout()
plt.savefig("1.bTrayectoria.pdf")

# Velocidades
plt.subplot(2,2,2)
plt.plot(sol.t, vx, label="vx")
plt.plot(sol.t, vy, label="vy")
plt.xlabel("t")
plt.ylabel("Velocidad")
plt.legend()
plt.title("Velocidades vs tiempo")
plt.grid(True)
plt.tight_layout()
plt.savefig("1.bVelocidad.pdf")

# Momento conjugado
plt.subplot(2,2,3)
plt.plot(sol.t, Pi_y)
plt.xlabel("t")
plt.ylabel(r"$\Pi_y$")
plt.title("Momento conjugado")
plt.grid(True)
plt.tight_layout()
plt.savefig("1.bMomentoConjugado.pdf")

# Energía total
plt.subplot(2,2,4)
plt.plot(sol.t, E_tot)
plt.xlabel("t")
plt.ylabel("Energía total")
plt.title("Conservación de energía")
plt.grid(True)

plt.tight_layout()
plt.savefig("1.bEnergiaTotal.pdf")

#1.c  Sistema Binario
#1c

# Parámetros y condiciones iniciales indicadas en el enunciado para el sistema
G = 1.0
m = 1.7

# Sistema de ecuaciones diferenciales
def sistema(t, y):
    x1, y1, vx1, vy1, x2, y2, vx2, vy2 = y

    # Vector posición y distancia entre las estrellas
    r12 = np.array([x1 - x2, y1 - y2])
    dist = np.linalg.norm(r12)

    # Aceleraciones por gravitación
    a1 = -G * m * r12 / dist**3
    a2 =  G * m * r12 / dist**3

    return [vx1, vy1, a1[0], a1[1],
            vx2, vy2, a2[0], a2[1]]

# Condiciones iniciales
y0 = [0, 0, 0, 0.5,   # x1, y1, vx1, vy1
      1, 1, 0, -0.5]  # x2, y2, vx2, vy2

# Intervalo de integración
t_span = (0, 10)
t_eval = np.linspace(t_span[0], t_span[1], 2000)

# Resolver con RK45
sol = solve_ivp(sistema, t_span, y0, method="RK45", t_eval=t_eval, rtol=1e-9, atol=1e-12)

# Extraer soluciones
x1, y1 = sol.y[0], sol.y[1]
x2, y2 = sol.y[4], sol.y[5]

# Graficar trayectorias
plt.figure(figsize=(7,7))
plt.plot(x1, y1, label="Estrella 1 (m=1.7)", color="blue")
plt.plot(x2, y2, label="Estrella 2 (m=1.7)", color="red")
plt.scatter([x1[0], x2[0]], [y1[0], y2[0]], c=["blue","red"], marker="o", label="Posición inicial")
plt.xlabel("x")
plt.ylabel("y")
plt.title("Órbita de un sistema binario con RK45")
plt.legend()
plt.axis("equal")
plt.grid()

plt.tight_layout()
plt.savefig("1.c.pdf")

"""Punto 2"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from scipy.optimize import minimize_scalar

# Parámetros físicos
masa = 10.01
gravedad = 9.773
A = 1.642
B = 40.624
C = 2.36

# Coeficiente beta dependiente de la altura
def beta(altura):
    return A * (1 - altura / B) ** C

# Ecuaciones del movimiento con rozamiento
def movimiento(t, estado, angulo, velocidad_inicial):
    x, y, vx, vy = estado
    velocidad = np.sqrt(vx**2 + vy**2)

    beta_valor = beta(y)
    fuerza_friccion = beta_valor * velocidad**2 / masa

    ax = -fuerza_friccion * (vx / velocidad) if velocidad > 0 else 0
    ay = -gravedad - fuerza_friccion * (vy / velocidad) if velocidad > 0 else -gravedad

    return [vx, vy, ax, ay]

# Calcula el alcance para un ángulo dado
def calcular_alcance(angulo, velocidad_inicial, tiempo=(0, 20), rtol=1e-6, atol=1e-8):
    x0, y0 = 0, 0
    vx0 = velocidad_inicial * np.cos(np.radians(angulo))
    vy0 = velocidad_inicial * np.sin(np.radians(angulo))
    estado_inicial = [x0, y0, vx0, vy0]

    def toca_suelo(t, estado, angulo, velocidad_inicial):
        return estado[1]  # condición: y = 0
    toca_suelo.terminal = True
    toca_suelo.direction = -1

    sol = solve_ivp(movimiento, tiempo, estado_inicial,
                   args=(angulo, velocidad_inicial), events=toca_suelo,
                   rtol=rtol, atol=atol, dense_output=True)

    if sol.status == 1:
        return sol.y_events[0][0][0]  # x cuando toca suelo
    else:
        return sol.y[0][-1]

# Busca el ángulo que da el máximo alcance
def angulo_optimo(velocidad_inicial, rango_angulos=(10, 80)):
    def negativo_alcance(angulo):
        return -calcular_alcance(angulo, velocidad_inicial)

    resultado = minimize_scalar(negativo_alcance, bounds=rango_angulos, method='bounded')
    angulo_mejor = resultado.x
    alcance_max = -resultado.fun

    return angulo_mejor, alcance_max

# Simulación para distintos valores de velocidad inicial
velocidades = np.linspace(10, 140, 50)
alcances_maximos = []
angulos_optimos = []

for v0 in velocidades:
    angulo_mejor, alcance_max = angulo_optimo(v0)
    angulos_optimos.append(angulo_mejor)
    alcances_maximos.append(alcance_max)
    print(f"v0 = {v0:.1f} m/s, ángulo óptimo = {angulo_mejor:.2f}°, alcance máximo = {alcance_max:.2f} m")

# Gráfica
plt.figure(figsize=(10, 6))
plt.plot(velocidades, alcances_maximos, 'b-', linewidth=2)
plt.xlabel('Velocidad inicial $v_0$ (m/s)')
plt.ylabel('Alcance máximo $x_{max}$ (m)')
plt.title('Alcance máximo vs Velocidad inicial')
plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.savefig('2.a.pdf', dpi=300, bbox_inches='tight')
plt.show()

"""Circuito génetico"""

#Usando 𝛼0 = 𝛼/1000 y 𝑛 = 2, encuentre la amplitud de oscilación final (después de ≈ 10oscilaciones) de 𝑝3 para cada combinación de parámetros 𝛼 y beta
def circuito_genetico(ts,y,alpha,betha,n=2):
  m1, m2, m3, p1, p2, p3 = y
  alpha0 = alpha  / 1000.0

  dm1 = alpha  / (1 + p3**n) + alpha0 - m1
  dm2 = alpha / (1 + p1**n) + alpha0 - m2
  dm3 = alpha  / (1 + p2**n) + alpha0 - m3

  dp1 = -betha * (p1 - m1)
  dp2 = -betha * (p2 - m2)
  dp3 = -betha * (p3 - m3)

  return [dm1, dm2, dm3, dp1, dp2, dp3]

dt = 0.01
t = np.arange(0,400,dt)
alphas = np.logspace(0, 5, 20)
bethas = np.logspace(0, 2, 20)
y0 = [1, 0, 0, 0, 0, 0]
amplitudes = np.zeros((len(bethas), len(alphas)))

for i, betha in enumerate(bethas):
  for j,alpha in enumerate(alphas):
    sol = solve_ivp(circuito_genetico, (0, 400), y0, args=(alpha, betha), t_eval=t)
    p3 = sol.y[5]
    peaks, _ = find_peaks(p3, distance=20)

    if len(peaks) > 10:
       mask = peaks[10]
    else:
       mask = int(0.5*len(t))
    p3s = p3[mask:]
    amplitudes[i, j] = np.max(p3s) - np.min(p3s)

plt.figure(figsize=(8,6))
plt.pcolormesh(alphas, bethas, amplitudes, shading="auto", cmap="viridis")
plt.xscale("log"); plt.yscale("log")
plt.xlabel(r"$\alpha$")
plt.ylabel(r"$\beta$")
plt.colorbar(label="Amplitud de p3")
plt.title("Amplitud")
plt.tight_layout()
plt.savefig('5.pdf', bbox_inches='tight', pad_inches=0.1)

"""Péndulo"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from joblib import Parallel, delayed

def F(t,Y, alpha):
    tetha,r,Pt,Pr = Y
    dtetha = Pt/(r+1)**2
    dr = Pr
    dPt=-(alpha**2)*np.sin(tetha)*(r+1)
    dPr= (alpha**2)*np.cos(tetha)-r+(Pt**2)/(r+1)**3
    return [dtetha,dr,dPt,dPr]

def evento(t,Y,*args):
    return Y[0]
evento.terminal = False
evento.direction = -1

tmax = 10**4
ts = np.linspace(0,tmax,400)
y0 = [np.pi/2, 0.0, 0.0, 0.0]
alphas = np.linspace(1,1.2,20)

def solucion(alpha):
    sol = solve_ivp(F, (0, tmax), y0, args=(alpha,),
                   events=evento)
    return alpha, sol.t_events, sol.y_events

res = Parallel(n_jobs=-1)(delayed(solucion)(alpha) for alpha in alphas)

plt.figure(figsize=(12, 8))
colors = plt.cm.jet(np.linspace(0, 1, len(alphas)))

for i, (alpha, t_events, y_events) in enumerate(res):
    if len(y_events[0]) > 0:
        r = y_events[0][:, 1]   # r
        Pr = y_events[0][:, 3]  # Pr
        plt.scatter(r, Pr, s=10, alpha=0.7,
                   color=colors[i], label=f'α={alpha:.2f}')

plt.xlabel("r")
plt.ylabel("Pr")
plt.title(" Pr vs r para θ = 0")
plt.grid()
plt.legend()
plt.tight_layout()
plt.savefig('4.pdf', dpi=300, bbox_inches='tight')

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import pandas as pd

def lane_emden_ivp(x, S, n):
    theta, y = S
    dtheta_dx = y
    dy_dx = -theta**n - (2/x)*y
    return [dtheta_dx, dy_dx]

def evento_primer_cero(x, S, n):
    return S[0]
evento_primer_cero.terminal = True
evento_primer_cero.direction = -1

n_values = [0.0, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0]
resultados = []

fig, ax = plt.subplots(figsize=(10, 6))

for i, n in enumerate(n_values):
    x0 = 1e-6
    theta0 = 1 - (x0**2)/6
    dtheta0 = -x0/3
    S0 = [theta0, dtheta0]

    color = plt.cm.tab10(i / len(n_values))

    if n != 5.0:
        sol_ext = solve_ivp(
            lane_emden_ivp,
            [x0, 35],
            S0,
            args=(n,),
            dense_output=True,
            rtol=1e-12,
            atol=1e-12,
            max_step=0.01
        )

        sol_phys = solve_ivp(
            lane_emden_ivp,
            [x0, 35],
            S0,
            args=(n,),
            events=lambda x, S, n=n: evento_primer_cero(x, S, n),
            dense_output=True,
            rtol=1e-12,
            atol=1e-12,
            max_step=0.01
        )

        if sol_phys.t_events[0].size > 0:
            xs = sol_phys.t_events[0][0]
            theta_xs, dtheta_xs = sol_phys.sol(xs)
            M = -xs**2 * dtheta_xs
            rho_ratio = -(1/3) * xs / dtheta_xs
        else:
            xs, M, rho_ratio = np.nan, np.nan, np.nan

        resultados.append([n, xs, M, rho_ratio])


        x_phys = np.linspace(x0, xs, 300)
        y_phys = sol_phys.sol(x_phys)
        ax.plot(x_phys, y_phys[0], color=color, label=f'n = {n}')

        x_ext = np.linspace(x0, 35, 1000)
        y_ext = sol_ext.sol(x_ext)
        ax.plot(x_ext, y_ext[0], linestyle='-', color=color, alpha=0.5, label=f'n = {n}')

    else:
        # n=5
        def theta_n5(x):
            return 1.0 / np.sqrt(1 + x**2 / 3)

        x_plot = np.linspace(0, 35, 1000)
        theta_plot = theta_n5(x_plot)
        ax.plot(x_plot, theta_plot, color=color, label="n = 5 (analítico)")
        xs = np.inf
        M = np.pi * np.sqrt(3)
        rho_ratio = np.inf
        resultados.append([n, xs, M, rho_ratio])

df = pd.DataFrame(resultados, columns=["Índice n", "Radio", "Masa", "ρ_c / ρ̄"])
df.to_csv("7.csv", index=False)

ax.set_xlabel('Radio adimensional $x$')
ax.set_ylabel('Densidad relativa $\\theta(x)$')
ax.set_title('Perfil de densidad estelar (Lane-Emden)')
ax.set_xlim(0, 25)
ax.set_ylim(-0.5, 1.5)
ax.grid(True)
ax.axhline(0, color='gray', linestyle='--')
ax.legend(title="Índice politrópico", loc='upper right', frameon=True)
plt.tight_layout()
plt.savefig('7.png')